{
//=========Macro generated from canvas: c_ControlRegion_1/
//=========  (Sun Jun 21 12:53:05 2015) by ROOT version5.34/18
   TCanvas *c_ControlRegion_1 = new TCanvas("c_ControlRegion_1", "",0,0,800,800);
   gStyle->SetOptStat(0);
   c_ControlRegion_1->SetHighLightColor(2);
   c_ControlRegion_1->Range(0,0,1,1);
   c_ControlRegion_1->SetFillColor(0);
   c_ControlRegion_1->SetBorderMode(0);
   c_ControlRegion_1->SetBorderSize(2);
   c_ControlRegion_1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: p1
   TPad *p1 = new TPad("p1", "p1",0,0.28,1,1);
   p1->Draw();
   p1->cd();
   p1->Range(156.25,-2.2528,1093.75,0.8423349);
   p1->SetFillColor(0);
   p1->SetBorderMode(0);
   p1->SetBorderSize(2);
   p1->SetLogy();
   p1->SetBottomMargin(0.01);
   p1->SetFrameBorderMode(0);
   p1->SetFrameBorderMode(0);
   Double_t xAxis14[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_data_control_region_ControlRegion_1__14 = new TH1F("boosted_data_control_region_ControlRegion_1__14","",6, xAxis14);
   boosted_data_control_region_ControlRegion_1__14->SetBinContent(1,1.62);
   boosted_data_control_region_ControlRegion_1__14->SetBinContent(2,0.64);
   boosted_data_control_region_ControlRegion_1__14->SetBinContent(3,0.52);
   boosted_data_control_region_ControlRegion_1__14->SetBinContent(4,0.22);
   boosted_data_control_region_ControlRegion_1__14->SetBinContent(5,0.16);
   boosted_data_control_region_ControlRegion_1__14->SetBinContent(6,0.018);
   boosted_data_control_region_ControlRegion_1__14->SetBinError(1,0.18);
   boosted_data_control_region_ControlRegion_1__14->SetBinError(2,0.1131371);
   boosted_data_control_region_ControlRegion_1__14->SetBinError(3,0.1019804);
   boosted_data_control_region_ControlRegion_1__14->SetBinError(4,0.0663325);
   boosted_data_control_region_ControlRegion_1__14->SetBinError(5,0.05656854);
   boosted_data_control_region_ControlRegion_1__14->SetBinError(6,0.006);
   boosted_data_control_region_ControlRegion_1__14->SetEntries(12);
   boosted_data_control_region_ControlRegion_1__14->SetDirectory(0);
   boosted_data_control_region_ControlRegion_1__14->SetLineWidth(2);
   boosted_data_control_region_ControlRegion_1__14->SetMarkerStyle(20);
   boosted_data_control_region_ControlRegion_1__14->GetXaxis()->SetTitle("fake MET (GeV)");
   boosted_data_control_region_ControlRegion_1__14->GetXaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__14->GetXaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_1__14->GetXaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_1__14->GetXaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__14->GetYaxis()->SetTitle("Events/GeV");
   boosted_data_control_region_ControlRegion_1__14->GetYaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__14->GetYaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_1__14->GetYaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_1__14->GetYaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__14->GetZaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__14->GetZaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_1__14->GetZaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_1__14->GetZaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__14->Draw("Pe");
   Double_t xAxis15[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_control_region_ControlRegion_1__15 = new TH1F("boosted_control_region_ControlRegion_1__15","Expected ControlRegion_1 control region",6, xAxis15);
   boosted_control_region_ControlRegion_1__15->SetBinContent(1,1.900936);
   boosted_control_region_ControlRegion_1__15->SetBinContent(2,0.8534553);
   boosted_control_region_ControlRegion_1__15->SetBinContent(3,0.3783584);
   boosted_control_region_ControlRegion_1__15->SetBinContent(4,0.1705274);
   boosted_control_region_ControlRegion_1__15->SetBinContent(5,0.1035137);
   boosted_control_region_ControlRegion_1__15->SetBinContent(6,0.01531547);
   boosted_control_region_ControlRegion_1__15->SetBinError(1,0.1050974);
   boosted_control_region_ControlRegion_1__15->SetBinError(2,0.06381136);
   boosted_control_region_ControlRegion_1__15->SetBinError(3,0.03826793);
   boosted_control_region_ControlRegion_1__15->SetBinError(4,0.02260525);
   boosted_control_region_ControlRegion_1__15->SetBinError(5,0.01702195);
   boosted_control_region_ControlRegion_1__15->SetBinError(6,0.002702513);
   boosted_control_region_ControlRegion_1__15->SetEntries(12);
   boosted_control_region_ControlRegion_1__15->SetDirectory(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ccccff");
   boosted_control_region_ControlRegion_1__15->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   boosted_control_region_ControlRegion_1__15->SetLineColor(ci);
   boosted_control_region_ControlRegion_1__15->SetLineWidth(2);
   boosted_control_region_ControlRegion_1__15->GetXaxis()->SetLabelFont(42);
   boosted_control_region_ControlRegion_1__15->GetXaxis()->SetLabelSize(0.035);
   boosted_control_region_ControlRegion_1__15->GetXaxis()->SetTitleSize(0.035);
   boosted_control_region_ControlRegion_1__15->GetXaxis()->SetTitleFont(42);
   boosted_control_region_ControlRegion_1__15->GetYaxis()->SetTitle("Events/GeV");
   boosted_control_region_ControlRegion_1__15->GetYaxis()->SetLabelFont(42);
   boosted_control_region_ControlRegion_1__15->GetYaxis()->SetLabelSize(0.035);
   boosted_control_region_ControlRegion_1__15->GetYaxis()->SetTitleSize(0.035);
   boosted_control_region_ControlRegion_1__15->GetYaxis()->SetTitleFont(42);
   boosted_control_region_ControlRegion_1__15->GetZaxis()->SetLabelFont(42);
   boosted_control_region_ControlRegion_1__15->GetZaxis()->SetLabelSize(0.035);
   boosted_control_region_ControlRegion_1__15->GetZaxis()->SetTitleSize(0.035);
   boosted_control_region_ControlRegion_1__15->GetZaxis()->SetTitleFont(42);
   boosted_control_region_ControlRegion_1__15->Draw("sameE2");
   Double_t xAxis16[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *control_region_ControlRegion_1__16 = new TH1F("control_region_ControlRegion_1__16","Expected ControlRegion_1 control region",6, xAxis16);
   control_region_ControlRegion_1__16->SetBinContent(1,1.744096);
   control_region_ControlRegion_1__16->SetBinContent(2,0.8738768);
   control_region_ControlRegion_1__16->SetBinContent(3,0.3689697);
   control_region_ControlRegion_1__16->SetBinContent(4,0.1903547);
   control_region_ControlRegion_1__16->SetBinContent(5,0.107835);
   control_region_ControlRegion_1__16->SetBinContent(6,0.01304173);
   control_region_ControlRegion_1__16->SetEntries(12);
   control_region_ControlRegion_1__16->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   control_region_ControlRegion_1__16->SetLineColor(ci);
   control_region_ControlRegion_1__16->SetLineWidth(2);
   control_region_ControlRegion_1__16->GetXaxis()->SetLabelFont(42);
   control_region_ControlRegion_1__16->GetXaxis()->SetLabelSize(0.035);
   control_region_ControlRegion_1__16->GetXaxis()->SetTitleSize(0.035);
   control_region_ControlRegion_1__16->GetXaxis()->SetTitleFont(42);
   control_region_ControlRegion_1__16->GetYaxis()->SetTitle("Events/GeV");
   control_region_ControlRegion_1__16->GetYaxis()->SetLabelFont(42);
   control_region_ControlRegion_1__16->GetYaxis()->SetLabelSize(0.035);
   control_region_ControlRegion_1__16->GetYaxis()->SetTitleSize(0.035);
   control_region_ControlRegion_1__16->GetYaxis()->SetTitleFont(42);
   control_region_ControlRegion_1__16->GetZaxis()->SetLabelFont(42);
   control_region_ControlRegion_1__16->GetZaxis()->SetLabelSize(0.035);
   control_region_ControlRegion_1__16->GetZaxis()->SetTitleSize(0.035);
   control_region_ControlRegion_1__16->GetZaxis()->SetTitleFont(42);
   control_region_ControlRegion_1__16->Draw("samehist");
   Double_t xAxis17[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_control_region_ControlRegion_1__17 = new TH1F("boosted_control_region_ControlRegion_1__17","Expected ControlRegion_1 control region",6, xAxis17);
   boosted_control_region_ControlRegion_1__17->SetBinContent(1,1.900936);
   boosted_control_region_ControlRegion_1__17->SetBinContent(2,0.8534553);
   boosted_control_region_ControlRegion_1__17->SetBinContent(3,0.3783584);
   boosted_control_region_ControlRegion_1__17->SetBinContent(4,0.1705274);
   boosted_control_region_ControlRegion_1__17->SetBinContent(5,0.1035137);
   boosted_control_region_ControlRegion_1__17->SetBinContent(6,0.01531547);
   boosted_control_region_ControlRegion_1__17->SetBinError(1,0.1050974);
   boosted_control_region_ControlRegion_1__17->SetBinError(2,0.06381136);
   boosted_control_region_ControlRegion_1__17->SetBinError(3,0.03826793);
   boosted_control_region_ControlRegion_1__17->SetBinError(4,0.02260525);
   boosted_control_region_ControlRegion_1__17->SetBinError(5,0.01702195);
   boosted_control_region_ControlRegion_1__17->SetBinError(6,0.002702513);
   boosted_control_region_ControlRegion_1__17->SetEntries(12);
   boosted_control_region_ControlRegion_1__17->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   boosted_control_region_ControlRegion_1__17->SetLineColor(ci);
   boosted_control_region_ControlRegion_1__17->SetLineWidth(2);
   boosted_control_region_ControlRegion_1__17->GetXaxis()->SetLabelFont(42);
   boosted_control_region_ControlRegion_1__17->GetXaxis()->SetLabelSize(0.035);
   boosted_control_region_ControlRegion_1__17->GetXaxis()->SetTitleSize(0.035);
   boosted_control_region_ControlRegion_1__17->GetXaxis()->SetTitleFont(42);
   boosted_control_region_ControlRegion_1__17->GetYaxis()->SetTitle("Events/GeV");
   boosted_control_region_ControlRegion_1__17->GetYaxis()->SetLabelFont(42);
   boosted_control_region_ControlRegion_1__17->GetYaxis()->SetLabelSize(0.035);
   boosted_control_region_ControlRegion_1__17->GetYaxis()->SetTitleSize(0.035);
   boosted_control_region_ControlRegion_1__17->GetYaxis()->SetTitleFont(42);
   boosted_control_region_ControlRegion_1__17->GetZaxis()->SetLabelFont(42);
   boosted_control_region_ControlRegion_1__17->GetZaxis()->SetLabelSize(0.035);
   boosted_control_region_ControlRegion_1__17->GetZaxis()->SetTitleSize(0.035);
   boosted_control_region_ControlRegion_1__17->GetZaxis()->SetTitleFont(42);
   boosted_control_region_ControlRegion_1__17->Draw("histsame");
   Double_t xAxis18[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_mc_control_region_ControlRegion_1__18 = new TH1F("boosted_mc_control_region_ControlRegion_1__18","Background ControlRegion_1 control region",6, xAxis18);
   boosted_mc_control_region_ControlRegion_1__18->SetBinContent(1,0.3121006);
   boosted_mc_control_region_ControlRegion_1__18->SetBinContent(2,0.1676487);
   boosted_mc_control_region_ControlRegion_1__18->SetBinContent(3,0.08312856);
   boosted_mc_control_region_ControlRegion_1__18->SetBinContent(4,0.03935155);
   boosted_mc_control_region_ControlRegion_1__18->SetBinContent(5,0.03146074);
   boosted_mc_control_region_ControlRegion_1__18->SetBinContent(6,0.002607076);
   boosted_mc_control_region_ControlRegion_1__18->SetBinError(1,0.0790064);
   boosted_mc_control_region_ControlRegion_1__18->SetBinError(2,0.05790487);
   boosted_mc_control_region_ControlRegion_1__18->SetBinError(3,0.04077464);
   boosted_mc_control_region_ControlRegion_1__18->SetBinError(4,0.02805407);
   boosted_mc_control_region_ControlRegion_1__18->SetBinError(5,0.02508416);
   boosted_mc_control_region_ControlRegion_1__18->SetBinError(6,0.002283452);
   boosted_mc_control_region_ControlRegion_1__18->SetEntries(12);
   boosted_mc_control_region_ControlRegion_1__18->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   boosted_mc_control_region_ControlRegion_1__18->SetFillColor(ci);
   boosted_mc_control_region_ControlRegion_1__18->SetLineWidth(2);
   boosted_mc_control_region_ControlRegion_1__18->GetXaxis()->SetLabelFont(42);
   boosted_mc_control_region_ControlRegion_1__18->GetXaxis()->SetLabelSize(0.035);
   boosted_mc_control_region_ControlRegion_1__18->GetXaxis()->SetTitleSize(0.035);
   boosted_mc_control_region_ControlRegion_1__18->GetXaxis()->SetTitleFont(42);
   boosted_mc_control_region_ControlRegion_1__18->GetYaxis()->SetTitle("Events/GeV");
   boosted_mc_control_region_ControlRegion_1__18->GetYaxis()->SetLabelFont(42);
   boosted_mc_control_region_ControlRegion_1__18->GetYaxis()->SetLabelSize(0.035);
   boosted_mc_control_region_ControlRegion_1__18->GetYaxis()->SetTitleSize(0.035);
   boosted_mc_control_region_ControlRegion_1__18->GetYaxis()->SetTitleFont(42);
   boosted_mc_control_region_ControlRegion_1__18->GetZaxis()->SetLabelFont(42);
   boosted_mc_control_region_ControlRegion_1__18->GetZaxis()->SetLabelSize(0.035);
   boosted_mc_control_region_ControlRegion_1__18->GetZaxis()->SetTitleSize(0.035);
   boosted_mc_control_region_ControlRegion_1__18->GetZaxis()->SetTitleFont(42);
   boosted_mc_control_region_ControlRegion_1__18->Draw("samehist");
   Double_t xAxis19[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_data_control_region_ControlRegion_1__19 = new TH1F("boosted_data_control_region_ControlRegion_1__19","",6, xAxis19);
   boosted_data_control_region_ControlRegion_1__19->SetBinContent(1,1.62);
   boosted_data_control_region_ControlRegion_1__19->SetBinContent(2,0.64);
   boosted_data_control_region_ControlRegion_1__19->SetBinContent(3,0.52);
   boosted_data_control_region_ControlRegion_1__19->SetBinContent(4,0.22);
   boosted_data_control_region_ControlRegion_1__19->SetBinContent(5,0.16);
   boosted_data_control_region_ControlRegion_1__19->SetBinContent(6,0.018);
   boosted_data_control_region_ControlRegion_1__19->SetBinError(1,0.18);
   boosted_data_control_region_ControlRegion_1__19->SetBinError(2,0.1131371);
   boosted_data_control_region_ControlRegion_1__19->SetBinError(3,0.1019804);
   boosted_data_control_region_ControlRegion_1__19->SetBinError(4,0.0663325);
   boosted_data_control_region_ControlRegion_1__19->SetBinError(5,0.05656854);
   boosted_data_control_region_ControlRegion_1__19->SetBinError(6,0.006);
   boosted_data_control_region_ControlRegion_1__19->SetEntries(12);
   boosted_data_control_region_ControlRegion_1__19->SetDirectory(0);
   boosted_data_control_region_ControlRegion_1__19->SetLineWidth(2);
   boosted_data_control_region_ControlRegion_1__19->SetMarkerStyle(20);
   boosted_data_control_region_ControlRegion_1__19->GetXaxis()->SetTitle("fake MET (GeV)");
   boosted_data_control_region_ControlRegion_1__19->GetXaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__19->GetXaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_1__19->GetXaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_1__19->GetXaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__19->GetYaxis()->SetTitle("Events/GeV");
   boosted_data_control_region_ControlRegion_1__19->GetYaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__19->GetYaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_1__19->GetYaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_1__19->GetYaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__19->GetZaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__19->GetZaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_1__19->GetZaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_1__19->GetZaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__19->Draw("Pesame");
   
   TLegend *leg = new TLegend(0.54,0.53,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("boosted_data_control_region_ControlRegion_1","Data - Dimuon","PEL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("boosted_control_region_ControlRegion_1","Expected (post-fit)","FL");

   ci = TColor::GetColor("#ccccff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("boosted_mc_control_region_ControlRegion_1","Backgrounds Component","F");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("control_region_ControlRegion_1","Expected (pre-fit)","L");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.1,0.92,"#bf{CMS} #it{Preliminary}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis20[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_data_control_region_ControlRegion_1__20 = new TH1F("boosted_data_control_region_ControlRegion_1__20","",6, xAxis20);
   boosted_data_control_region_ControlRegion_1__20->SetBinContent(1,1.62);
   boosted_data_control_region_ControlRegion_1__20->SetBinContent(2,0.64);
   boosted_data_control_region_ControlRegion_1__20->SetBinContent(3,0.52);
   boosted_data_control_region_ControlRegion_1__20->SetBinContent(4,0.22);
   boosted_data_control_region_ControlRegion_1__20->SetBinContent(5,0.16);
   boosted_data_control_region_ControlRegion_1__20->SetBinContent(6,0.018);
   boosted_data_control_region_ControlRegion_1__20->SetBinError(1,0.18);
   boosted_data_control_region_ControlRegion_1__20->SetBinError(2,0.1131371);
   boosted_data_control_region_ControlRegion_1__20->SetBinError(3,0.1019804);
   boosted_data_control_region_ControlRegion_1__20->SetBinError(4,0.0663325);
   boosted_data_control_region_ControlRegion_1__20->SetBinError(5,0.05656854);
   boosted_data_control_region_ControlRegion_1__20->SetBinError(6,0.006);
   boosted_data_control_region_ControlRegion_1__20->SetEntries(12);
   boosted_data_control_region_ControlRegion_1__20->SetDirectory(0);
   boosted_data_control_region_ControlRegion_1__20->SetLineWidth(2);
   boosted_data_control_region_ControlRegion_1__20->SetMarkerStyle(20);
   boosted_data_control_region_ControlRegion_1__20->GetXaxis()->SetTitle("fake MET (GeV)");
   boosted_data_control_region_ControlRegion_1__20->GetXaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__20->GetXaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_1__20->GetXaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_1__20->GetXaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__20->GetYaxis()->SetTitle("Events/GeV");
   boosted_data_control_region_ControlRegion_1__20->GetYaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__20->GetYaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_1__20->GetYaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_1__20->GetYaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__20->GetZaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__20->GetZaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_1__20->GetZaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_1__20->GetZaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__20->Draw("sameaxis");
   p1->Modified();
   c_ControlRegion_1->cd();
  
// ------------>Primitives in pad: p2
   p2 = new TPad("p2", "p2",0,0.068,1,0.285);
   p2->Draw();
   p2->cd();
   p2->Range(156.25,0.02627906,1093.75,1.863488);
   p2->SetFillColor(0);
   p2->SetBorderMode(0);
   p2->SetBorderSize(2);
   p2->SetTopMargin(0.04);
   p2->SetFrameBorderMode(0);
   p2->SetFrameBorderMode(0);
   Double_t xAxis21[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_data_control_region_ControlRegion_1__21 = new TH1F("boosted_data_control_region_ControlRegion_1__21","",6, xAxis21);
   boosted_data_control_region_ControlRegion_1__21->SetBinContent(1,0.8522119);
   boosted_data_control_region_ControlRegion_1__21->SetBinContent(2,0.7498928);
   boosted_data_control_region_ControlRegion_1__21->SetBinContent(3,1.374358);
   boosted_data_control_region_ControlRegion_1__21->SetBinContent(4,1.290115);
   boosted_data_control_region_ControlRegion_1__21->SetBinContent(5,1.545689);
   boosted_data_control_region_ControlRegion_1__21->SetBinContent(6,1.175282);
   boosted_data_control_region_ControlRegion_1__21->SetBinError(1,0.09469021);
   boosted_data_control_region_ControlRegion_1__21->SetBinError(2,0.1325636);
   boosted_data_control_region_ControlRegion_1__21->SetBinError(3,0.2695338);
   boosted_data_control_region_ControlRegion_1__21->SetBinError(4,0.3889844);
   boosted_data_control_region_ControlRegion_1__21->SetBinError(5,0.5464835);
   boosted_data_control_region_ControlRegion_1__21->SetBinError(6,0.3917607);
   boosted_data_control_region_ControlRegion_1__21->SetMinimum(0.21);
   boosted_data_control_region_ControlRegion_1__21->SetMaximum(1.79);
   boosted_data_control_region_ControlRegion_1__21->SetEntries(69.49137);
   boosted_data_control_region_ControlRegion_1__21->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   boosted_data_control_region_ControlRegion_1__21->SetLineColor(ci);
   boosted_data_control_region_ControlRegion_1__21->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   boosted_data_control_region_ControlRegion_1__21->SetMarkerColor(ci);
   boosted_data_control_region_ControlRegion_1__21->SetMarkerStyle(20);
   boosted_data_control_region_ControlRegion_1__21->GetXaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__21->GetXaxis()->SetLabelSize(0.12);
   boosted_data_control_region_ControlRegion_1__21->GetXaxis()->SetTitleSize(0.085);
   boosted_data_control_region_ControlRegion_1__21->GetXaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__21->GetYaxis()->SetTitle("Data/Bkg");
   boosted_data_control_region_ControlRegion_1__21->GetYaxis()->SetNdivisions(5);
   boosted_data_control_region_ControlRegion_1__21->GetYaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__21->GetYaxis()->SetLabelSize(0.1);
   boosted_data_control_region_ControlRegion_1__21->GetYaxis()->SetTitleSize(0.12);
   boosted_data_control_region_ControlRegion_1__21->GetYaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__21->GetZaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__21->GetZaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_1__21->GetZaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_1__21->GetZaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__21->Draw("");
   Double_t xAxis22[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *OneWithError_boosted_data_control_region_ControlRegion_1__22 = new TH1F("OneWithError_boosted_data_control_region_ControlRegion_1__22","",6, xAxis22);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetBinContent(1,1);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetBinContent(2,1);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetBinContent(3,1);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetBinContent(4,1);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetBinContent(5,1);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetBinContent(6,1);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetBinError(1,0.05528721);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetBinError(2,0.07476825);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetBinError(3,0.101142);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetBinError(4,0.1325608);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetBinError(5,0.1644415);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetBinError(6,0.1764564);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetMinimum(0.21);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetMaximum(1.79);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetEntries(75.49137);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetDirectory(0);

   ci = TColor::GetColor("#ccccff");
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetFillColor(ci);

   ci = TColor::GetColor("#ccccff");
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetLineColor(ci);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetMarkerColor(ci);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetMarkerStyle(20);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->SetMarkerSize(0);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->GetXaxis()->SetLabelFont(42);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->GetXaxis()->SetLabelSize(0.12);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->GetXaxis()->SetTitleSize(0.085);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->GetXaxis()->SetTitleFont(42);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->GetYaxis()->SetTitle("Data/Bkg");
   OneWithError_boosted_data_control_region_ControlRegion_1__22->GetYaxis()->SetNdivisions(5);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->GetYaxis()->SetLabelFont(42);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->GetYaxis()->SetLabelSize(0.1);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->GetYaxis()->SetTitleSize(0.12);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->GetYaxis()->SetTitleFont(42);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->GetZaxis()->SetLabelFont(42);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->GetZaxis()->SetLabelSize(0.035);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->GetZaxis()->SetTitleSize(0.035);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->GetZaxis()->SetTitleFont(42);
   OneWithError_boosted_data_control_region_ControlRegion_1__22->Draw("sameE2");
   TLine *line = new TLine(250,1,1000,1);
   line->SetLineStyle(2);
   line->SetLineWidth(2);
   line->Draw();
   Double_t xAxis23[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_data_control_region_ControlRegion_1__23 = new TH1F("boosted_data_control_region_ControlRegion_1__23","",6, xAxis23);
   boosted_data_control_region_ControlRegion_1__23->SetBinContent(1,0.8522119);
   boosted_data_control_region_ControlRegion_1__23->SetBinContent(2,0.7498928);
   boosted_data_control_region_ControlRegion_1__23->SetBinContent(3,1.374358);
   boosted_data_control_region_ControlRegion_1__23->SetBinContent(4,1.290115);
   boosted_data_control_region_ControlRegion_1__23->SetBinContent(5,1.545689);
   boosted_data_control_region_ControlRegion_1__23->SetBinContent(6,1.175282);
   boosted_data_control_region_ControlRegion_1__23->SetBinError(1,0.09469021);
   boosted_data_control_region_ControlRegion_1__23->SetBinError(2,0.1325636);
   boosted_data_control_region_ControlRegion_1__23->SetBinError(3,0.2695338);
   boosted_data_control_region_ControlRegion_1__23->SetBinError(4,0.3889844);
   boosted_data_control_region_ControlRegion_1__23->SetBinError(5,0.5464835);
   boosted_data_control_region_ControlRegion_1__23->SetBinError(6,0.3917607);
   boosted_data_control_region_ControlRegion_1__23->SetMinimum(0.21);
   boosted_data_control_region_ControlRegion_1__23->SetMaximum(1.79);
   boosted_data_control_region_ControlRegion_1__23->SetEntries(69.49137);
   boosted_data_control_region_ControlRegion_1__23->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   boosted_data_control_region_ControlRegion_1__23->SetLineColor(ci);
   boosted_data_control_region_ControlRegion_1__23->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   boosted_data_control_region_ControlRegion_1__23->SetMarkerColor(ci);
   boosted_data_control_region_ControlRegion_1__23->SetMarkerStyle(20);
   boosted_data_control_region_ControlRegion_1__23->GetXaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__23->GetXaxis()->SetLabelSize(0.12);
   boosted_data_control_region_ControlRegion_1__23->GetXaxis()->SetTitleSize(0.085);
   boosted_data_control_region_ControlRegion_1__23->GetXaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__23->GetYaxis()->SetTitle("Data/Bkg");
   boosted_data_control_region_ControlRegion_1__23->GetYaxis()->SetNdivisions(5);
   boosted_data_control_region_ControlRegion_1__23->GetYaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__23->GetYaxis()->SetLabelSize(0.1);
   boosted_data_control_region_ControlRegion_1__23->GetYaxis()->SetTitleSize(0.12);
   boosted_data_control_region_ControlRegion_1__23->GetYaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__23->GetZaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__23->GetZaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_1__23->GetZaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_1__23->GetZaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__23->Draw("same");
   Double_t xAxis24[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_data_control_region_ControlRegion_1__24 = new TH1F("boosted_data_control_region_ControlRegion_1__24","",6, xAxis24);
   boosted_data_control_region_ControlRegion_1__24->SetBinContent(1,0.9288478);
   boosted_data_control_region_ControlRegion_1__24->SetBinContent(2,0.7323686);
   boosted_data_control_region_ControlRegion_1__24->SetBinContent(3,1.40933);
   boosted_data_control_region_ControlRegion_1__24->SetBinContent(4,1.155737);
   boosted_data_control_region_ControlRegion_1__24->SetBinContent(5,1.483748);
   boosted_data_control_region_ControlRegion_1__24->SetBinContent(6,1.380185);
   boosted_data_control_region_ControlRegion_1__24->SetBinError(1,0.1032053);
   boosted_data_control_region_ControlRegion_1__24->SetBinError(2,0.1294657);
   boosted_data_control_region_ControlRegion_1__24->SetBinError(3,0.2763923);
   boosted_data_control_region_ControlRegion_1__24->SetBinError(4,0.3484679);
   boosted_data_control_region_ControlRegion_1__24->SetBinError(5,0.5245842);
   boosted_data_control_region_ControlRegion_1__24->SetBinError(6,0.4600618);
   boosted_data_control_region_ControlRegion_1__24->SetEntries(70.59758);
   boosted_data_control_region_ControlRegion_1__24->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   boosted_data_control_region_ControlRegion_1__24->SetLineColor(ci);
   boosted_data_control_region_ControlRegion_1__24->SetLineWidth(2);

   ci = TColor::GetColor("#ff0000");
   boosted_data_control_region_ControlRegion_1__24->SetMarkerColor(ci);
   boosted_data_control_region_ControlRegion_1__24->SetMarkerStyle(20);
   boosted_data_control_region_ControlRegion_1__24->GetXaxis()->SetTitle("fake MET (GeV)");
   boosted_data_control_region_ControlRegion_1__24->GetXaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__24->GetXaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_1__24->GetXaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_1__24->GetXaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__24->GetYaxis()->SetTitle("Events/GeV");
   boosted_data_control_region_ControlRegion_1__24->GetYaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__24->GetYaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_1__24->GetYaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_1__24->GetYaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__24->GetZaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__24->GetZaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_1__24->GetZaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_1__24->GetZaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__24->Draw("pelsame");
   Double_t xAxis25[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_data_control_region_ControlRegion_1__25 = new TH1F("boosted_data_control_region_ControlRegion_1__25","",6, xAxis25);
   boosted_data_control_region_ControlRegion_1__25->SetBinContent(1,0.8522119);
   boosted_data_control_region_ControlRegion_1__25->SetBinContent(2,0.7498928);
   boosted_data_control_region_ControlRegion_1__25->SetBinContent(3,1.374358);
   boosted_data_control_region_ControlRegion_1__25->SetBinContent(4,1.290115);
   boosted_data_control_region_ControlRegion_1__25->SetBinContent(5,1.545689);
   boosted_data_control_region_ControlRegion_1__25->SetBinContent(6,1.175282);
   boosted_data_control_region_ControlRegion_1__25->SetBinError(1,0.09469021);
   boosted_data_control_region_ControlRegion_1__25->SetBinError(2,0.1325636);
   boosted_data_control_region_ControlRegion_1__25->SetBinError(3,0.2695338);
   boosted_data_control_region_ControlRegion_1__25->SetBinError(4,0.3889844);
   boosted_data_control_region_ControlRegion_1__25->SetBinError(5,0.5464835);
   boosted_data_control_region_ControlRegion_1__25->SetBinError(6,0.3917607);
   boosted_data_control_region_ControlRegion_1__25->SetMinimum(0.21);
   boosted_data_control_region_ControlRegion_1__25->SetMaximum(1.79);
   boosted_data_control_region_ControlRegion_1__25->SetEntries(69.49137);
   boosted_data_control_region_ControlRegion_1__25->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   boosted_data_control_region_ControlRegion_1__25->SetLineColor(ci);
   boosted_data_control_region_ControlRegion_1__25->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   boosted_data_control_region_ControlRegion_1__25->SetMarkerColor(ci);
   boosted_data_control_region_ControlRegion_1__25->SetMarkerStyle(20);
   boosted_data_control_region_ControlRegion_1__25->GetXaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__25->GetXaxis()->SetLabelSize(0.12);
   boosted_data_control_region_ControlRegion_1__25->GetXaxis()->SetTitleSize(0.085);
   boosted_data_control_region_ControlRegion_1__25->GetXaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__25->GetYaxis()->SetTitle("Data/Bkg");
   boosted_data_control_region_ControlRegion_1__25->GetYaxis()->SetNdivisions(5);
   boosted_data_control_region_ControlRegion_1__25->GetYaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__25->GetYaxis()->SetLabelSize(0.1);
   boosted_data_control_region_ControlRegion_1__25->GetYaxis()->SetTitleSize(0.12);
   boosted_data_control_region_ControlRegion_1__25->GetYaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__25->GetZaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__25->GetZaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_1__25->GetZaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_1__25->GetZaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__25->Draw("samepel");
   Double_t xAxis26[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_data_control_region_ControlRegion_1__26 = new TH1F("boosted_data_control_region_ControlRegion_1__26","",6, xAxis26);
   boosted_data_control_region_ControlRegion_1__26->SetBinContent(1,0.8522119);
   boosted_data_control_region_ControlRegion_1__26->SetBinContent(2,0.7498928);
   boosted_data_control_region_ControlRegion_1__26->SetBinContent(3,1.374358);
   boosted_data_control_region_ControlRegion_1__26->SetBinContent(4,1.290115);
   boosted_data_control_region_ControlRegion_1__26->SetBinContent(5,1.545689);
   boosted_data_control_region_ControlRegion_1__26->SetBinContent(6,1.175282);
   boosted_data_control_region_ControlRegion_1__26->SetBinError(1,0.09469021);
   boosted_data_control_region_ControlRegion_1__26->SetBinError(2,0.1325636);
   boosted_data_control_region_ControlRegion_1__26->SetBinError(3,0.2695338);
   boosted_data_control_region_ControlRegion_1__26->SetBinError(4,0.3889844);
   boosted_data_control_region_ControlRegion_1__26->SetBinError(5,0.5464835);
   boosted_data_control_region_ControlRegion_1__26->SetBinError(6,0.3917607);
   boosted_data_control_region_ControlRegion_1__26->SetMinimum(0.21);
   boosted_data_control_region_ControlRegion_1__26->SetMaximum(1.79);
   boosted_data_control_region_ControlRegion_1__26->SetEntries(69.49137);
   boosted_data_control_region_ControlRegion_1__26->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   boosted_data_control_region_ControlRegion_1__26->SetLineColor(ci);
   boosted_data_control_region_ControlRegion_1__26->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   boosted_data_control_region_ControlRegion_1__26->SetMarkerColor(ci);
   boosted_data_control_region_ControlRegion_1__26->SetMarkerStyle(20);
   boosted_data_control_region_ControlRegion_1__26->GetXaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__26->GetXaxis()->SetLabelSize(0.12);
   boosted_data_control_region_ControlRegion_1__26->GetXaxis()->SetTitleSize(0.085);
   boosted_data_control_region_ControlRegion_1__26->GetXaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__26->GetYaxis()->SetTitle("Data/Bkg");
   boosted_data_control_region_ControlRegion_1__26->GetYaxis()->SetNdivisions(5);
   boosted_data_control_region_ControlRegion_1__26->GetYaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__26->GetYaxis()->SetLabelSize(0.1);
   boosted_data_control_region_ControlRegion_1__26->GetYaxis()->SetTitleSize(0.12);
   boosted_data_control_region_ControlRegion_1__26->GetYaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__26->GetZaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_1__26->GetZaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_1__26->GetZaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_1__26->GetZaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_1__26->Draw("sameaxis");
   p2->Modified();
   c_ControlRegion_1->cd();
      tex = new TLatex(0.7,0.94,"boosted category");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.7,0.03,"fake MET (GeV)");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   c_ControlRegion_1->Modified();
   c_ControlRegion_1->cd();
   c_ControlRegion_1->SetSelected(c_ControlRegion_1);
}
