{
//=========Macro generated from canvas: c_ControlRegion_0/
//=========  (Sun Jun 21 12:53:10 2015) by ROOT version5.34/18
   TCanvas *c_ControlRegion_0 = new TCanvas("c_ControlRegion_0", "",0,0,800,800);
   gStyle->SetOptStat(0);
   c_ControlRegion_0->SetHighLightColor(2);
   c_ControlRegion_0->Range(0,0,1,1);
   c_ControlRegion_0->SetFillColor(0);
   c_ControlRegion_0->SetBorderMode(0);
   c_ControlRegion_0->SetBorderSize(2);
   c_ControlRegion_0->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: p1
   TPad *p1 = new TPad("p1", "p1",0,0.28,1,1);
   p1->Draw();
   p1->cd();
   p1->Range(156.25,-2.598695,1093.75,1.423524);
   p1->SetFillColor(0);
   p1->SetBorderMode(0);
   p1->SetBorderSize(2);
   p1->SetLogy();
   p1->SetBottomMargin(0.01);
   p1->SetFrameBorderMode(0);
   p1->SetFrameBorderMode(0);
   Double_t xAxis1[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_data_control_region_ControlRegion_0__1 = new TH1F("resolved_data_control_region_ControlRegion_0__1","",6, xAxis1);
   resolved_data_control_region_ControlRegion_0__1->SetBinContent(1,5.22);
   resolved_data_control_region_ControlRegion_0__1->SetBinContent(2,1.62);
   resolved_data_control_region_ControlRegion_0__1->SetBinContent(3,0.7);
   resolved_data_control_region_ControlRegion_0__1->SetBinContent(4,0.32);
   resolved_data_control_region_ControlRegion_0__1->SetBinContent(5,0.04);
   resolved_data_control_region_ControlRegion_0__1->SetBinContent(6,0.01);
   resolved_data_control_region_ControlRegion_0__1->SetBinError(1,0.3231099);
   resolved_data_control_region_ControlRegion_0__1->SetBinError(2,0.18);
   resolved_data_control_region_ControlRegion_0__1->SetBinError(3,0.1183216);
   resolved_data_control_region_ControlRegion_0__1->SetBinError(4,0.08);
   resolved_data_control_region_ControlRegion_0__1->SetBinError(5,0.02828427);
   resolved_data_control_region_ControlRegion_0__1->SetBinError(6,0.004472136);
   resolved_data_control_region_ControlRegion_0__1->SetEntries(12);
   resolved_data_control_region_ControlRegion_0__1->SetDirectory(0);
   resolved_data_control_region_ControlRegion_0__1->SetLineWidth(2);
   resolved_data_control_region_ControlRegion_0__1->SetMarkerStyle(20);
   resolved_data_control_region_ControlRegion_0__1->GetXaxis()->SetTitle("fake MET (GeV)");
   resolved_data_control_region_ControlRegion_0__1->GetXaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__1->GetXaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_0__1->GetXaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_0__1->GetXaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__1->GetYaxis()->SetTitle("Events/GeV");
   resolved_data_control_region_ControlRegion_0__1->GetYaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__1->GetYaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_0__1->GetYaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_0__1->GetYaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__1->GetZaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__1->GetZaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_0__1->GetZaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_0__1->GetZaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__1->Draw("Pe");
   Double_t xAxis2[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_control_region_ControlRegion_0__2 = new TH1F("resolved_control_region_ControlRegion_0__2","Expected ControlRegion_0 control region",6, xAxis2);
   resolved_control_region_ControlRegion_0__2->SetBinContent(1,5.219858);
   resolved_control_region_ControlRegion_0__2->SetBinContent(2,1.619509);
   resolved_control_region_ControlRegion_0__2->SetBinContent(3,0.6999348);
   resolved_control_region_ControlRegion_0__2->SetBinContent(4,0.3200313);
   resolved_control_region_ControlRegion_0__2->SetBinContent(5,0.04005849);
   resolved_control_region_ControlRegion_0__2->SetBinContent(6,0.01001169);
   resolved_control_region_ControlRegion_0__2->SetBinError(1,0.3262011);
   resolved_control_region_ControlRegion_0__2->SetBinError(2,0.1842712);
   resolved_control_region_ControlRegion_0__2->SetBinError(3,0.14903);
   resolved_control_region_ControlRegion_0__2->SetBinError(4,0.06536761);
   resolved_control_region_ControlRegion_0__2->SetBinError(5,0.01499404);
   resolved_control_region_ControlRegion_0__2->SetBinError(6,0.003395791);
   resolved_control_region_ControlRegion_0__2->SetEntries(12);
   resolved_control_region_ControlRegion_0__2->SetDirectory(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ccccff");
   resolved_control_region_ControlRegion_0__2->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   resolved_control_region_ControlRegion_0__2->SetLineColor(ci);
   resolved_control_region_ControlRegion_0__2->SetLineWidth(2);
   resolved_control_region_ControlRegion_0__2->GetXaxis()->SetLabelFont(42);
   resolved_control_region_ControlRegion_0__2->GetXaxis()->SetLabelSize(0.035);
   resolved_control_region_ControlRegion_0__2->GetXaxis()->SetTitleSize(0.035);
   resolved_control_region_ControlRegion_0__2->GetXaxis()->SetTitleFont(42);
   resolved_control_region_ControlRegion_0__2->GetYaxis()->SetTitle("Events/GeV");
   resolved_control_region_ControlRegion_0__2->GetYaxis()->SetLabelFont(42);
   resolved_control_region_ControlRegion_0__2->GetYaxis()->SetLabelSize(0.035);
   resolved_control_region_ControlRegion_0__2->GetYaxis()->SetTitleSize(0.035);
   resolved_control_region_ControlRegion_0__2->GetYaxis()->SetTitleFont(42);
   resolved_control_region_ControlRegion_0__2->GetZaxis()->SetLabelFont(42);
   resolved_control_region_ControlRegion_0__2->GetZaxis()->SetLabelSize(0.035);
   resolved_control_region_ControlRegion_0__2->GetZaxis()->SetTitleSize(0.035);
   resolved_control_region_ControlRegion_0__2->GetZaxis()->SetTitleFont(42);
   resolved_control_region_ControlRegion_0__2->Draw("sameE2");
   Double_t xAxis3[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *control_region_ControlRegion_0__3 = new TH1F("control_region_ControlRegion_0__3","Expected ControlRegion_0 control region",6, xAxis3);
   control_region_ControlRegion_0__3->SetBinContent(1,5.555992);
   control_region_ControlRegion_0__3->SetBinContent(2,1.839754);
   control_region_ControlRegion_0__3->SetBinContent(3,0.5021085);
   control_region_ControlRegion_0__3->SetBinContent(4,0.2372169);
   control_region_ControlRegion_0__3->SetBinContent(5,0.04403099);
   control_region_ControlRegion_0__3->SetBinContent(6,0.0157053);
   control_region_ControlRegion_0__3->SetEntries(12);
   control_region_ControlRegion_0__3->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   control_region_ControlRegion_0__3->SetLineColor(ci);
   control_region_ControlRegion_0__3->SetLineWidth(2);
   control_region_ControlRegion_0__3->GetXaxis()->SetLabelFont(42);
   control_region_ControlRegion_0__3->GetXaxis()->SetLabelSize(0.035);
   control_region_ControlRegion_0__3->GetXaxis()->SetTitleSize(0.035);
   control_region_ControlRegion_0__3->GetXaxis()->SetTitleFont(42);
   control_region_ControlRegion_0__3->GetYaxis()->SetTitle("Events/GeV");
   control_region_ControlRegion_0__3->GetYaxis()->SetLabelFont(42);
   control_region_ControlRegion_0__3->GetYaxis()->SetLabelSize(0.035);
   control_region_ControlRegion_0__3->GetYaxis()->SetTitleSize(0.035);
   control_region_ControlRegion_0__3->GetYaxis()->SetTitleFont(42);
   control_region_ControlRegion_0__3->GetZaxis()->SetLabelFont(42);
   control_region_ControlRegion_0__3->GetZaxis()->SetLabelSize(0.035);
   control_region_ControlRegion_0__3->GetZaxis()->SetTitleSize(0.035);
   control_region_ControlRegion_0__3->GetZaxis()->SetTitleFont(42);
   control_region_ControlRegion_0__3->Draw("samehist");
   Double_t xAxis4[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_control_region_ControlRegion_0__4 = new TH1F("resolved_control_region_ControlRegion_0__4","Expected ControlRegion_0 control region",6, xAxis4);
   resolved_control_region_ControlRegion_0__4->SetBinContent(1,5.219858);
   resolved_control_region_ControlRegion_0__4->SetBinContent(2,1.619509);
   resolved_control_region_ControlRegion_0__4->SetBinContent(3,0.6999348);
   resolved_control_region_ControlRegion_0__4->SetBinContent(4,0.3200313);
   resolved_control_region_ControlRegion_0__4->SetBinContent(5,0.04005849);
   resolved_control_region_ControlRegion_0__4->SetBinContent(6,0.01001169);
   resolved_control_region_ControlRegion_0__4->SetBinError(1,0.3262011);
   resolved_control_region_ControlRegion_0__4->SetBinError(2,0.1842712);
   resolved_control_region_ControlRegion_0__4->SetBinError(3,0.14903);
   resolved_control_region_ControlRegion_0__4->SetBinError(4,0.06536761);
   resolved_control_region_ControlRegion_0__4->SetBinError(5,0.01499404);
   resolved_control_region_ControlRegion_0__4->SetBinError(6,0.003395791);
   resolved_control_region_ControlRegion_0__4->SetEntries(12);
   resolved_control_region_ControlRegion_0__4->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   resolved_control_region_ControlRegion_0__4->SetLineColor(ci);
   resolved_control_region_ControlRegion_0__4->SetLineWidth(2);
   resolved_control_region_ControlRegion_0__4->GetXaxis()->SetLabelFont(42);
   resolved_control_region_ControlRegion_0__4->GetXaxis()->SetLabelSize(0.035);
   resolved_control_region_ControlRegion_0__4->GetXaxis()->SetTitleSize(0.035);
   resolved_control_region_ControlRegion_0__4->GetXaxis()->SetTitleFont(42);
   resolved_control_region_ControlRegion_0__4->GetYaxis()->SetTitle("Events/GeV");
   resolved_control_region_ControlRegion_0__4->GetYaxis()->SetLabelFont(42);
   resolved_control_region_ControlRegion_0__4->GetYaxis()->SetLabelSize(0.035);
   resolved_control_region_ControlRegion_0__4->GetYaxis()->SetTitleSize(0.035);
   resolved_control_region_ControlRegion_0__4->GetYaxis()->SetTitleFont(42);
   resolved_control_region_ControlRegion_0__4->GetZaxis()->SetLabelFont(42);
   resolved_control_region_ControlRegion_0__4->GetZaxis()->SetLabelSize(0.035);
   resolved_control_region_ControlRegion_0__4->GetZaxis()->SetTitleSize(0.035);
   resolved_control_region_ControlRegion_0__4->GetZaxis()->SetTitleFont(42);
   resolved_control_region_ControlRegion_0__4->Draw("histsame");
   Double_t xAxis5[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_mc_control_region_ControlRegion_0__5 = new TH1F("resolved_mc_control_region_ControlRegion_0__5","Background ControlRegion_0 control region",6, xAxis5);
   resolved_mc_control_region_ControlRegion_0__5->SetBinContent(1,1.98475);
   resolved_mc_control_region_ControlRegion_0__5->SetBinContent(2,0.6490707);
   resolved_mc_control_region_ControlRegion_0__5->SetBinContent(3,0.1964993);
   resolved_mc_control_region_ControlRegion_0__5->SetBinContent(4,0.07661451);
   resolved_mc_control_region_ControlRegion_0__5->SetBinContent(5,0.02862851);
   resolved_mc_control_region_ControlRegion_0__5->SetBinContent(6,0.002472739);
   resolved_mc_control_region_ControlRegion_0__5->SetBinError(1,0.199236);
   resolved_mc_control_region_ControlRegion_0__5->SetBinError(2,0.113936);
   resolved_mc_control_region_ControlRegion_0__5->SetBinError(3,0.0626896);
   resolved_mc_control_region_ControlRegion_0__5->SetBinError(4,0.03914448);
   resolved_mc_control_region_ControlRegion_0__5->SetBinError(5,0.02392844);
   resolved_mc_control_region_ControlRegion_0__5->SetBinError(6,0.002223843);
   resolved_mc_control_region_ControlRegion_0__5->SetEntries(12);
   resolved_mc_control_region_ControlRegion_0__5->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   resolved_mc_control_region_ControlRegion_0__5->SetFillColor(ci);
   resolved_mc_control_region_ControlRegion_0__5->SetLineWidth(2);
   resolved_mc_control_region_ControlRegion_0__5->GetXaxis()->SetLabelFont(42);
   resolved_mc_control_region_ControlRegion_0__5->GetXaxis()->SetLabelSize(0.035);
   resolved_mc_control_region_ControlRegion_0__5->GetXaxis()->SetTitleSize(0.035);
   resolved_mc_control_region_ControlRegion_0__5->GetXaxis()->SetTitleFont(42);
   resolved_mc_control_region_ControlRegion_0__5->GetYaxis()->SetTitle("Events/GeV");
   resolved_mc_control_region_ControlRegion_0__5->GetYaxis()->SetLabelFont(42);
   resolved_mc_control_region_ControlRegion_0__5->GetYaxis()->SetLabelSize(0.035);
   resolved_mc_control_region_ControlRegion_0__5->GetYaxis()->SetTitleSize(0.035);
   resolved_mc_control_region_ControlRegion_0__5->GetYaxis()->SetTitleFont(42);
   resolved_mc_control_region_ControlRegion_0__5->GetZaxis()->SetLabelFont(42);
   resolved_mc_control_region_ControlRegion_0__5->GetZaxis()->SetLabelSize(0.035);
   resolved_mc_control_region_ControlRegion_0__5->GetZaxis()->SetTitleSize(0.035);
   resolved_mc_control_region_ControlRegion_0__5->GetZaxis()->SetTitleFont(42);
   resolved_mc_control_region_ControlRegion_0__5->Draw("samehist");
   Double_t xAxis6[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_data_control_region_ControlRegion_0__6 = new TH1F("resolved_data_control_region_ControlRegion_0__6","",6, xAxis6);
   resolved_data_control_region_ControlRegion_0__6->SetBinContent(1,5.22);
   resolved_data_control_region_ControlRegion_0__6->SetBinContent(2,1.62);
   resolved_data_control_region_ControlRegion_0__6->SetBinContent(3,0.7);
   resolved_data_control_region_ControlRegion_0__6->SetBinContent(4,0.32);
   resolved_data_control_region_ControlRegion_0__6->SetBinContent(5,0.04);
   resolved_data_control_region_ControlRegion_0__6->SetBinContent(6,0.01);
   resolved_data_control_region_ControlRegion_0__6->SetBinError(1,0.3231099);
   resolved_data_control_region_ControlRegion_0__6->SetBinError(2,0.18);
   resolved_data_control_region_ControlRegion_0__6->SetBinError(3,0.1183216);
   resolved_data_control_region_ControlRegion_0__6->SetBinError(4,0.08);
   resolved_data_control_region_ControlRegion_0__6->SetBinError(5,0.02828427);
   resolved_data_control_region_ControlRegion_0__6->SetBinError(6,0.004472136);
   resolved_data_control_region_ControlRegion_0__6->SetEntries(12);
   resolved_data_control_region_ControlRegion_0__6->SetDirectory(0);
   resolved_data_control_region_ControlRegion_0__6->SetLineWidth(2);
   resolved_data_control_region_ControlRegion_0__6->SetMarkerStyle(20);
   resolved_data_control_region_ControlRegion_0__6->GetXaxis()->SetTitle("fake MET (GeV)");
   resolved_data_control_region_ControlRegion_0__6->GetXaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__6->GetXaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_0__6->GetXaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_0__6->GetXaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__6->GetYaxis()->SetTitle("Events/GeV");
   resolved_data_control_region_ControlRegion_0__6->GetYaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__6->GetYaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_0__6->GetYaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_0__6->GetYaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__6->GetZaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__6->GetZaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_0__6->GetZaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_0__6->GetZaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__6->Draw("Pesame");
   
   TLegend *leg = new TLegend(0.54,0.53,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("resolved_data_control_region_ControlRegion_0","Data - Single muon","PEL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("resolved_control_region_ControlRegion_0","Expected (post-fit)","FL");

   ci = TColor::GetColor("#ccccff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("resolved_mc_control_region_ControlRegion_0","Backgrounds Component","F");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("control_region_ControlRegion_0","Expected (pre-fit)","L");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.1,0.92,"#bf{CMS} #it{Preliminary}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis7[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_data_control_region_ControlRegion_0__7 = new TH1F("resolved_data_control_region_ControlRegion_0__7","",6, xAxis7);
   resolved_data_control_region_ControlRegion_0__7->SetBinContent(1,5.22);
   resolved_data_control_region_ControlRegion_0__7->SetBinContent(2,1.62);
   resolved_data_control_region_ControlRegion_0__7->SetBinContent(3,0.7);
   resolved_data_control_region_ControlRegion_0__7->SetBinContent(4,0.32);
   resolved_data_control_region_ControlRegion_0__7->SetBinContent(5,0.04);
   resolved_data_control_region_ControlRegion_0__7->SetBinContent(6,0.01);
   resolved_data_control_region_ControlRegion_0__7->SetBinError(1,0.3231099);
   resolved_data_control_region_ControlRegion_0__7->SetBinError(2,0.18);
   resolved_data_control_region_ControlRegion_0__7->SetBinError(3,0.1183216);
   resolved_data_control_region_ControlRegion_0__7->SetBinError(4,0.08);
   resolved_data_control_region_ControlRegion_0__7->SetBinError(5,0.02828427);
   resolved_data_control_region_ControlRegion_0__7->SetBinError(6,0.004472136);
   resolved_data_control_region_ControlRegion_0__7->SetEntries(12);
   resolved_data_control_region_ControlRegion_0__7->SetDirectory(0);
   resolved_data_control_region_ControlRegion_0__7->SetLineWidth(2);
   resolved_data_control_region_ControlRegion_0__7->SetMarkerStyle(20);
   resolved_data_control_region_ControlRegion_0__7->GetXaxis()->SetTitle("fake MET (GeV)");
   resolved_data_control_region_ControlRegion_0__7->GetXaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__7->GetXaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_0__7->GetXaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_0__7->GetXaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__7->GetYaxis()->SetTitle("Events/GeV");
   resolved_data_control_region_ControlRegion_0__7->GetYaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__7->GetYaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_0__7->GetYaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_0__7->GetYaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__7->GetZaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__7->GetZaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_0__7->GetZaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_0__7->GetZaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__7->Draw("sameaxis");
   p1->Modified();
   c_ControlRegion_0->cd();
  
// ------------>Primitives in pad: p2
   p2 = new TPad("p2", "p2",0,0.068,1,0.285);
   p2->Draw();
   p2->cd();
   p2->Range(156.25,0.02627906,1093.75,1.863488);
   p2->SetFillColor(0);
   p2->SetBorderMode(0);
   p2->SetBorderSize(2);
   p2->SetTopMargin(0.04);
   p2->SetFrameBorderMode(0);
   p2->SetFrameBorderMode(0);
   Double_t xAxis8[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_data_control_region_ControlRegion_0__8 = new TH1F("resolved_data_control_region_ControlRegion_0__8","",6, xAxis8);
   resolved_data_control_region_ControlRegion_0__8->SetBinContent(1,1.000027);
   resolved_data_control_region_ControlRegion_0__8->SetBinContent(2,1.000303);
   resolved_data_control_region_ControlRegion_0__8->SetBinContent(3,1.000093);
   resolved_data_control_region_ControlRegion_0__8->SetBinContent(4,0.9999021);
   resolved_data_control_region_ControlRegion_0__8->SetBinContent(5,0.9985397);
   resolved_data_control_region_ControlRegion_0__8->SetBinContent(6,0.998832);
   resolved_data_control_region_ControlRegion_0__8->SetBinError(1,0.06190013);
   resolved_data_control_region_ControlRegion_0__8->SetBinError(2,0.1111448);
   resolved_data_control_region_ControlRegion_0__8->SetBinError(3,0.1690466);
   resolved_data_control_region_ControlRegion_0__8->SetBinError(4,0.2499755);
   resolved_data_control_region_ControlRegion_0__8->SetBinError(5,0.7060743);
   resolved_data_control_region_ControlRegion_0__8->SetBinError(6,0.4466913);
   resolved_data_control_region_ControlRegion_0__8->SetMinimum(0.21);
   resolved_data_control_region_ControlRegion_0__8->SetMaximum(1.79);
   resolved_data_control_region_ControlRegion_0__8->SetEntries(44.66824);
   resolved_data_control_region_ControlRegion_0__8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   resolved_data_control_region_ControlRegion_0__8->SetLineColor(ci);
   resolved_data_control_region_ControlRegion_0__8->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   resolved_data_control_region_ControlRegion_0__8->SetMarkerColor(ci);
   resolved_data_control_region_ControlRegion_0__8->SetMarkerStyle(20);
   resolved_data_control_region_ControlRegion_0__8->GetXaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__8->GetXaxis()->SetLabelSize(0.12);
   resolved_data_control_region_ControlRegion_0__8->GetXaxis()->SetTitleSize(0.085);
   resolved_data_control_region_ControlRegion_0__8->GetXaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__8->GetYaxis()->SetTitle("Data/Bkg");
   resolved_data_control_region_ControlRegion_0__8->GetYaxis()->SetNdivisions(5);
   resolved_data_control_region_ControlRegion_0__8->GetYaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__8->GetYaxis()->SetLabelSize(0.1);
   resolved_data_control_region_ControlRegion_0__8->GetYaxis()->SetTitleSize(0.12);
   resolved_data_control_region_ControlRegion_0__8->GetYaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__8->GetZaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__8->GetZaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_0__8->GetZaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_0__8->GetZaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__8->Draw("");
   Double_t xAxis9[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *OneWithError_resolved_data_control_region_ControlRegion_0__9 = new TH1F("OneWithError_resolved_data_control_region_ControlRegion_0__9","",6, xAxis9);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetBinContent(1,1);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetBinContent(2,1);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetBinContent(3,1);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetBinContent(4,1);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetBinContent(5,1);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetBinContent(6,1);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetBinError(1,0.06249233);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetBinError(2,0.1137821);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetBinError(3,0.2129199);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetBinError(4,0.2042538);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetBinError(5,0.3743037);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetBinError(6,0.3391825);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetMinimum(0.21);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetMaximum(1.79);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetEntries(50.66824);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetDirectory(0);

   ci = TColor::GetColor("#ccccff");
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetFillColor(ci);

   ci = TColor::GetColor("#ccccff");
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetLineColor(ci);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetMarkerColor(ci);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetMarkerStyle(20);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->SetMarkerSize(0);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->GetXaxis()->SetLabelFont(42);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->GetXaxis()->SetLabelSize(0.12);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->GetXaxis()->SetTitleSize(0.085);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->GetXaxis()->SetTitleFont(42);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->GetYaxis()->SetTitle("Data/Bkg");
   OneWithError_resolved_data_control_region_ControlRegion_0__9->GetYaxis()->SetNdivisions(5);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->GetYaxis()->SetLabelFont(42);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->GetYaxis()->SetLabelSize(0.1);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->GetYaxis()->SetTitleSize(0.12);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->GetYaxis()->SetTitleFont(42);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->GetZaxis()->SetLabelFont(42);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->GetZaxis()->SetLabelSize(0.035);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->GetZaxis()->SetTitleSize(0.035);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->GetZaxis()->SetTitleFont(42);
   OneWithError_resolved_data_control_region_ControlRegion_0__9->Draw("sameE2");
   TLine *line = new TLine(250,1,1000,1);
   line->SetLineStyle(2);
   line->SetLineWidth(2);
   line->Draw();
   Double_t xAxis10[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_data_control_region_ControlRegion_0__10 = new TH1F("resolved_data_control_region_ControlRegion_0__10","",6, xAxis10);
   resolved_data_control_region_ControlRegion_0__10->SetBinContent(1,1.000027);
   resolved_data_control_region_ControlRegion_0__10->SetBinContent(2,1.000303);
   resolved_data_control_region_ControlRegion_0__10->SetBinContent(3,1.000093);
   resolved_data_control_region_ControlRegion_0__10->SetBinContent(4,0.9999021);
   resolved_data_control_region_ControlRegion_0__10->SetBinContent(5,0.9985397);
   resolved_data_control_region_ControlRegion_0__10->SetBinContent(6,0.998832);
   resolved_data_control_region_ControlRegion_0__10->SetBinError(1,0.06190013);
   resolved_data_control_region_ControlRegion_0__10->SetBinError(2,0.1111448);
   resolved_data_control_region_ControlRegion_0__10->SetBinError(3,0.1690466);
   resolved_data_control_region_ControlRegion_0__10->SetBinError(4,0.2499755);
   resolved_data_control_region_ControlRegion_0__10->SetBinError(5,0.7060743);
   resolved_data_control_region_ControlRegion_0__10->SetBinError(6,0.4466913);
   resolved_data_control_region_ControlRegion_0__10->SetMinimum(0.21);
   resolved_data_control_region_ControlRegion_0__10->SetMaximum(1.79);
   resolved_data_control_region_ControlRegion_0__10->SetEntries(44.66824);
   resolved_data_control_region_ControlRegion_0__10->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   resolved_data_control_region_ControlRegion_0__10->SetLineColor(ci);
   resolved_data_control_region_ControlRegion_0__10->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   resolved_data_control_region_ControlRegion_0__10->SetMarkerColor(ci);
   resolved_data_control_region_ControlRegion_0__10->SetMarkerStyle(20);
   resolved_data_control_region_ControlRegion_0__10->GetXaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__10->GetXaxis()->SetLabelSize(0.12);
   resolved_data_control_region_ControlRegion_0__10->GetXaxis()->SetTitleSize(0.085);
   resolved_data_control_region_ControlRegion_0__10->GetXaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__10->GetYaxis()->SetTitle("Data/Bkg");
   resolved_data_control_region_ControlRegion_0__10->GetYaxis()->SetNdivisions(5);
   resolved_data_control_region_ControlRegion_0__10->GetYaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__10->GetYaxis()->SetLabelSize(0.1);
   resolved_data_control_region_ControlRegion_0__10->GetYaxis()->SetTitleSize(0.12);
   resolved_data_control_region_ControlRegion_0__10->GetYaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__10->GetZaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__10->GetZaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_0__10->GetZaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_0__10->GetZaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__10->Draw("same");
   Double_t xAxis11[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_data_control_region_ControlRegion_0__11 = new TH1F("resolved_data_control_region_ControlRegion_0__11","",6, xAxis11);
   resolved_data_control_region_ControlRegion_0__11->SetBinContent(1,0.9395262);
   resolved_data_control_region_ControlRegion_0__11->SetBinContent(2,0.8805523);
   resolved_data_control_region_ControlRegion_0__11->SetBinContent(3,1.394121);
   resolved_data_control_region_ControlRegion_0__11->SetBinContent(4,1.348976);
   resolved_data_control_region_ControlRegion_0__11->SetBinContent(5,0.908451);
   resolved_data_control_region_ControlRegion_0__11->SetBinContent(6,0.6367276);
   resolved_data_control_region_ControlRegion_0__11->SetBinError(1,0.05815521);
   resolved_data_control_region_ControlRegion_0__11->SetBinError(2,0.09783914);
   resolved_data_control_region_ControlRegion_0__11->SetBinError(3,0.2356495);
   resolved_data_control_region_ControlRegion_0__11->SetBinError(4,0.3372441);
   resolved_data_control_region_ControlRegion_0__11->SetBinError(5,0.6423719);
   resolved_data_control_region_ControlRegion_0__11->SetBinError(6,0.2847533);
   resolved_data_control_region_ControlRegion_0__11->SetEntries(55.19976);
   resolved_data_control_region_ControlRegion_0__11->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   resolved_data_control_region_ControlRegion_0__11->SetLineColor(ci);
   resolved_data_control_region_ControlRegion_0__11->SetLineWidth(2);

   ci = TColor::GetColor("#ff0000");
   resolved_data_control_region_ControlRegion_0__11->SetMarkerColor(ci);
   resolved_data_control_region_ControlRegion_0__11->SetMarkerStyle(20);
   resolved_data_control_region_ControlRegion_0__11->GetXaxis()->SetTitle("fake MET (GeV)");
   resolved_data_control_region_ControlRegion_0__11->GetXaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__11->GetXaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_0__11->GetXaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_0__11->GetXaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__11->GetYaxis()->SetTitle("Events/GeV");
   resolved_data_control_region_ControlRegion_0__11->GetYaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__11->GetYaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_0__11->GetYaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_0__11->GetYaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__11->GetZaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__11->GetZaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_0__11->GetZaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_0__11->GetZaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__11->Draw("pelsame");
   Double_t xAxis12[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_data_control_region_ControlRegion_0__12 = new TH1F("resolved_data_control_region_ControlRegion_0__12","",6, xAxis12);
   resolved_data_control_region_ControlRegion_0__12->SetBinContent(1,1.000027);
   resolved_data_control_region_ControlRegion_0__12->SetBinContent(2,1.000303);
   resolved_data_control_region_ControlRegion_0__12->SetBinContent(3,1.000093);
   resolved_data_control_region_ControlRegion_0__12->SetBinContent(4,0.9999021);
   resolved_data_control_region_ControlRegion_0__12->SetBinContent(5,0.9985397);
   resolved_data_control_region_ControlRegion_0__12->SetBinContent(6,0.998832);
   resolved_data_control_region_ControlRegion_0__12->SetBinError(1,0.06190013);
   resolved_data_control_region_ControlRegion_0__12->SetBinError(2,0.1111448);
   resolved_data_control_region_ControlRegion_0__12->SetBinError(3,0.1690466);
   resolved_data_control_region_ControlRegion_0__12->SetBinError(4,0.2499755);
   resolved_data_control_region_ControlRegion_0__12->SetBinError(5,0.7060743);
   resolved_data_control_region_ControlRegion_0__12->SetBinError(6,0.4466913);
   resolved_data_control_region_ControlRegion_0__12->SetMinimum(0.21);
   resolved_data_control_region_ControlRegion_0__12->SetMaximum(1.79);
   resolved_data_control_region_ControlRegion_0__12->SetEntries(44.66824);
   resolved_data_control_region_ControlRegion_0__12->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   resolved_data_control_region_ControlRegion_0__12->SetLineColor(ci);
   resolved_data_control_region_ControlRegion_0__12->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   resolved_data_control_region_ControlRegion_0__12->SetMarkerColor(ci);
   resolved_data_control_region_ControlRegion_0__12->SetMarkerStyle(20);
   resolved_data_control_region_ControlRegion_0__12->GetXaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__12->GetXaxis()->SetLabelSize(0.12);
   resolved_data_control_region_ControlRegion_0__12->GetXaxis()->SetTitleSize(0.085);
   resolved_data_control_region_ControlRegion_0__12->GetXaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__12->GetYaxis()->SetTitle("Data/Bkg");
   resolved_data_control_region_ControlRegion_0__12->GetYaxis()->SetNdivisions(5);
   resolved_data_control_region_ControlRegion_0__12->GetYaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__12->GetYaxis()->SetLabelSize(0.1);
   resolved_data_control_region_ControlRegion_0__12->GetYaxis()->SetTitleSize(0.12);
   resolved_data_control_region_ControlRegion_0__12->GetYaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__12->GetZaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__12->GetZaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_0__12->GetZaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_0__12->GetZaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__12->Draw("samepel");
   Double_t xAxis13[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_data_control_region_ControlRegion_0__13 = new TH1F("resolved_data_control_region_ControlRegion_0__13","",6, xAxis13);
   resolved_data_control_region_ControlRegion_0__13->SetBinContent(1,1.000027);
   resolved_data_control_region_ControlRegion_0__13->SetBinContent(2,1.000303);
   resolved_data_control_region_ControlRegion_0__13->SetBinContent(3,1.000093);
   resolved_data_control_region_ControlRegion_0__13->SetBinContent(4,0.9999021);
   resolved_data_control_region_ControlRegion_0__13->SetBinContent(5,0.9985397);
   resolved_data_control_region_ControlRegion_0__13->SetBinContent(6,0.998832);
   resolved_data_control_region_ControlRegion_0__13->SetBinError(1,0.06190013);
   resolved_data_control_region_ControlRegion_0__13->SetBinError(2,0.1111448);
   resolved_data_control_region_ControlRegion_0__13->SetBinError(3,0.1690466);
   resolved_data_control_region_ControlRegion_0__13->SetBinError(4,0.2499755);
   resolved_data_control_region_ControlRegion_0__13->SetBinError(5,0.7060743);
   resolved_data_control_region_ControlRegion_0__13->SetBinError(6,0.4466913);
   resolved_data_control_region_ControlRegion_0__13->SetMinimum(0.21);
   resolved_data_control_region_ControlRegion_0__13->SetMaximum(1.79);
   resolved_data_control_region_ControlRegion_0__13->SetEntries(44.66824);
   resolved_data_control_region_ControlRegion_0__13->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   resolved_data_control_region_ControlRegion_0__13->SetLineColor(ci);
   resolved_data_control_region_ControlRegion_0__13->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   resolved_data_control_region_ControlRegion_0__13->SetMarkerColor(ci);
   resolved_data_control_region_ControlRegion_0__13->SetMarkerStyle(20);
   resolved_data_control_region_ControlRegion_0__13->GetXaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__13->GetXaxis()->SetLabelSize(0.12);
   resolved_data_control_region_ControlRegion_0__13->GetXaxis()->SetTitleSize(0.085);
   resolved_data_control_region_ControlRegion_0__13->GetXaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__13->GetYaxis()->SetTitle("Data/Bkg");
   resolved_data_control_region_ControlRegion_0__13->GetYaxis()->SetNdivisions(5);
   resolved_data_control_region_ControlRegion_0__13->GetYaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__13->GetYaxis()->SetLabelSize(0.1);
   resolved_data_control_region_ControlRegion_0__13->GetYaxis()->SetTitleSize(0.12);
   resolved_data_control_region_ControlRegion_0__13->GetYaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__13->GetZaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_0__13->GetZaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_0__13->GetZaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_0__13->GetZaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_0__13->Draw("sameaxis");
   p2->Modified();
   c_ControlRegion_0->cd();
      tex = new TLatex(0.7,0.94,"resolved category");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.7,0.03,"fake MET (GeV)");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   c_ControlRegion_0->Modified();
   c_ControlRegion_0->cd();
   c_ControlRegion_0->SetSelected(c_ControlRegion_0);
}
