{
//=========Macro generated from canvas: c_ControlRegion_1/
//=========  (Sun Jun 21 12:53:07 2015) by ROOT version5.34/18
   TCanvas *c_ControlRegion_1 = new TCanvas("c_ControlRegion_1", "",0,0,800,800);
   gStyle->SetOptStat(0);
   c_ControlRegion_1->SetHighLightColor(2);
   c_ControlRegion_1->Range(0,0,1,1);
   c_ControlRegion_1->SetFillColor(0);
   c_ControlRegion_1->SetBorderMode(0);
   c_ControlRegion_1->SetBorderSize(2);
   c_ControlRegion_1->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: p1
   TPad *p1 = new TPad("p1", "p1",0,0.28,1,1);
   p1->Draw();
   p1->cd();
   p1->Range(156.25,-3.03699,1093.75,0.6620415);
   p1->SetFillColor(0);
   p1->SetBorderMode(0);
   p1->SetBorderSize(2);
   p1->SetLogy();
   p1->SetBottomMargin(0.01);
   p1->SetFrameBorderMode(0);
   p1->SetFrameBorderMode(0);
   Double_t xAxis14[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_data_control_region_ControlRegion_1__14 = new TH1F("resolved_data_control_region_ControlRegion_1__14","",6, xAxis14);
   resolved_data_control_region_ControlRegion_1__14->SetBinContent(1,0.9);
   resolved_data_control_region_ControlRegion_1__14->SetBinContent(2,0.34);
   resolved_data_control_region_ControlRegion_1__14->SetBinContent(3,0.04);
   resolved_data_control_region_ControlRegion_1__14->SetBinContent(4,0.02);
   resolved_data_control_region_ControlRegion_1__14->SetBinContent(6,0.002);
   resolved_data_control_region_ControlRegion_1__14->SetBinError(1,0.1341641);
   resolved_data_control_region_ControlRegion_1__14->SetBinError(2,0.08246211);
   resolved_data_control_region_ControlRegion_1__14->SetBinError(3,0.02828427);
   resolved_data_control_region_ControlRegion_1__14->SetBinError(4,0.02);
   resolved_data_control_region_ControlRegion_1__14->SetBinError(6,0.002);
   resolved_data_control_region_ControlRegion_1__14->SetEntries(12);
   resolved_data_control_region_ControlRegion_1__14->SetDirectory(0);
   resolved_data_control_region_ControlRegion_1__14->SetLineWidth(2);
   resolved_data_control_region_ControlRegion_1__14->SetMarkerStyle(20);
   resolved_data_control_region_ControlRegion_1__14->GetXaxis()->SetTitle("fake MET (GeV)");
   resolved_data_control_region_ControlRegion_1__14->GetXaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__14->GetXaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_1__14->GetXaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_1__14->GetXaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__14->GetYaxis()->SetTitle("Events/GeV");
   resolved_data_control_region_ControlRegion_1__14->GetYaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__14->GetYaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_1__14->GetYaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_1__14->GetYaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__14->GetZaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__14->GetZaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_1__14->GetZaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_1__14->GetZaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__14->Draw("Pe");
   Double_t xAxis15[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_control_region_ControlRegion_1__15 = new TH1F("resolved_control_region_ControlRegion_1__15","Expected ControlRegion_1 control region",6, xAxis15);
   resolved_control_region_ControlRegion_1__15->SetBinContent(1,0.8540737);
   resolved_control_region_ControlRegion_1__15->SetBinContent(2,0.3104676);
   resolved_control_region_ControlRegion_1__15->SetBinContent(3,0.08901159);
   resolved_control_region_ControlRegion_1__15->SetBinContent(4,0.0468557);
   resolved_control_region_ControlRegion_1__15->SetBinContent(5,0.02478712);
   resolved_control_region_ControlRegion_1__15->SetBinContent(6,0.002616795);
   resolved_control_region_ControlRegion_1__15->SetBinError(1,0.06212267);
   resolved_control_region_ControlRegion_1__15->SetBinError(2,0.03521828);
   resolved_control_region_ControlRegion_1__15->SetBinError(3,0.01797562);
   resolved_control_region_ControlRegion_1__15->SetBinError(4,0.01517084);
   resolved_control_region_ControlRegion_1__15->SetBinError(5,0.009833992);
   resolved_control_region_ControlRegion_1__15->SetBinError(6,0.001449877);
   resolved_control_region_ControlRegion_1__15->SetEntries(12);
   resolved_control_region_ControlRegion_1__15->SetDirectory(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ccccff");
   resolved_control_region_ControlRegion_1__15->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   resolved_control_region_ControlRegion_1__15->SetLineColor(ci);
   resolved_control_region_ControlRegion_1__15->SetLineWidth(2);
   resolved_control_region_ControlRegion_1__15->GetXaxis()->SetLabelFont(42);
   resolved_control_region_ControlRegion_1__15->GetXaxis()->SetLabelSize(0.035);
   resolved_control_region_ControlRegion_1__15->GetXaxis()->SetTitleSize(0.035);
   resolved_control_region_ControlRegion_1__15->GetXaxis()->SetTitleFont(42);
   resolved_control_region_ControlRegion_1__15->GetYaxis()->SetTitle("Events/GeV");
   resolved_control_region_ControlRegion_1__15->GetYaxis()->SetLabelFont(42);
   resolved_control_region_ControlRegion_1__15->GetYaxis()->SetLabelSize(0.035);
   resolved_control_region_ControlRegion_1__15->GetYaxis()->SetTitleSize(0.035);
   resolved_control_region_ControlRegion_1__15->GetYaxis()->SetTitleFont(42);
   resolved_control_region_ControlRegion_1__15->GetZaxis()->SetLabelFont(42);
   resolved_control_region_ControlRegion_1__15->GetZaxis()->SetLabelSize(0.035);
   resolved_control_region_ControlRegion_1__15->GetZaxis()->SetTitleSize(0.035);
   resolved_control_region_ControlRegion_1__15->GetZaxis()->SetTitleFont(42);
   resolved_control_region_ControlRegion_1__15->Draw("sameE2");
   Double_t xAxis16[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *control_region_ControlRegion_1__16 = new TH1F("control_region_ControlRegion_1__16","Expected ControlRegion_1 control region",6, xAxis16);
   control_region_ControlRegion_1__16->SetBinContent(1,0.7006375);
   control_region_ControlRegion_1__16->SetBinContent(2,0.241972);
   control_region_ControlRegion_1__16->SetBinContent(3,0.08421597);
   control_region_ControlRegion_1__16->SetBinContent(4,0.03412127);
   control_region_ControlRegion_1__16->SetBinContent(5,0.03032034);
   control_region_ControlRegion_1__16->SetBinContent(6,0.0022006);
   control_region_ControlRegion_1__16->SetEntries(12);
   control_region_ControlRegion_1__16->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   control_region_ControlRegion_1__16->SetLineColor(ci);
   control_region_ControlRegion_1__16->SetLineWidth(2);
   control_region_ControlRegion_1__16->GetXaxis()->SetLabelFont(42);
   control_region_ControlRegion_1__16->GetXaxis()->SetLabelSize(0.035);
   control_region_ControlRegion_1__16->GetXaxis()->SetTitleSize(0.035);
   control_region_ControlRegion_1__16->GetXaxis()->SetTitleFont(42);
   control_region_ControlRegion_1__16->GetYaxis()->SetTitle("Events/GeV");
   control_region_ControlRegion_1__16->GetYaxis()->SetLabelFont(42);
   control_region_ControlRegion_1__16->GetYaxis()->SetLabelSize(0.035);
   control_region_ControlRegion_1__16->GetYaxis()->SetTitleSize(0.035);
   control_region_ControlRegion_1__16->GetYaxis()->SetTitleFont(42);
   control_region_ControlRegion_1__16->GetZaxis()->SetLabelFont(42);
   control_region_ControlRegion_1__16->GetZaxis()->SetLabelSize(0.035);
   control_region_ControlRegion_1__16->GetZaxis()->SetTitleSize(0.035);
   control_region_ControlRegion_1__16->GetZaxis()->SetTitleFont(42);
   control_region_ControlRegion_1__16->Draw("samehist");
   Double_t xAxis17[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_control_region_ControlRegion_1__17 = new TH1F("resolved_control_region_ControlRegion_1__17","Expected ControlRegion_1 control region",6, xAxis17);
   resolved_control_region_ControlRegion_1__17->SetBinContent(1,0.8540737);
   resolved_control_region_ControlRegion_1__17->SetBinContent(2,0.3104676);
   resolved_control_region_ControlRegion_1__17->SetBinContent(3,0.08901159);
   resolved_control_region_ControlRegion_1__17->SetBinContent(4,0.0468557);
   resolved_control_region_ControlRegion_1__17->SetBinContent(5,0.02478712);
   resolved_control_region_ControlRegion_1__17->SetBinContent(6,0.002616795);
   resolved_control_region_ControlRegion_1__17->SetBinError(1,0.06212267);
   resolved_control_region_ControlRegion_1__17->SetBinError(2,0.03521828);
   resolved_control_region_ControlRegion_1__17->SetBinError(3,0.01797562);
   resolved_control_region_ControlRegion_1__17->SetBinError(4,0.01517084);
   resolved_control_region_ControlRegion_1__17->SetBinError(5,0.009833992);
   resolved_control_region_ControlRegion_1__17->SetBinError(6,0.001449877);
   resolved_control_region_ControlRegion_1__17->SetEntries(12);
   resolved_control_region_ControlRegion_1__17->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   resolved_control_region_ControlRegion_1__17->SetLineColor(ci);
   resolved_control_region_ControlRegion_1__17->SetLineWidth(2);
   resolved_control_region_ControlRegion_1__17->GetXaxis()->SetLabelFont(42);
   resolved_control_region_ControlRegion_1__17->GetXaxis()->SetLabelSize(0.035);
   resolved_control_region_ControlRegion_1__17->GetXaxis()->SetTitleSize(0.035);
   resolved_control_region_ControlRegion_1__17->GetXaxis()->SetTitleFont(42);
   resolved_control_region_ControlRegion_1__17->GetYaxis()->SetTitle("Events/GeV");
   resolved_control_region_ControlRegion_1__17->GetYaxis()->SetLabelFont(42);
   resolved_control_region_ControlRegion_1__17->GetYaxis()->SetLabelSize(0.035);
   resolved_control_region_ControlRegion_1__17->GetYaxis()->SetTitleSize(0.035);
   resolved_control_region_ControlRegion_1__17->GetYaxis()->SetTitleFont(42);
   resolved_control_region_ControlRegion_1__17->GetZaxis()->SetLabelFont(42);
   resolved_control_region_ControlRegion_1__17->GetZaxis()->SetLabelSize(0.035);
   resolved_control_region_ControlRegion_1__17->GetZaxis()->SetTitleSize(0.035);
   resolved_control_region_ControlRegion_1__17->GetZaxis()->SetTitleFont(42);
   resolved_control_region_ControlRegion_1__17->Draw("histsame");
   Double_t xAxis18[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_mc_control_region_ControlRegion_1__18 = new TH1F("resolved_mc_control_region_ControlRegion_1__18","Background ControlRegion_1 control region",6, xAxis18);
   resolved_mc_control_region_ControlRegion_1__18->SetBinContent(1,0.1725452);
   resolved_mc_control_region_ControlRegion_1__18->SetBinContent(2,0.06083487);
   resolved_mc_control_region_ControlRegion_1__18->SetBinContent(3,0.01739115);
   resolved_mc_control_region_ControlRegion_1__18->SetBinContent(4,0.009944134);
   resolved_mc_control_region_ControlRegion_1__18->SetBinContent(5,0.003786932);
   resolved_mc_control_region_ControlRegion_1__18->SetBinContent(6,4.084041e-05);
   resolved_mc_control_region_ControlRegion_1__18->SetBinError(1,0.0587444);
   resolved_mc_control_region_ControlRegion_1__18->SetBinError(2,0.03488119);
   resolved_mc_control_region_ControlRegion_1__18->SetBinError(3,0.01865001);
   resolved_mc_control_region_ControlRegion_1__18->SetBinError(4,0.01410258);
   resolved_mc_control_region_ControlRegion_1__18->SetBinError(5,0.008702795);
   resolved_mc_control_region_ControlRegion_1__18->SetBinError(6,0.0002857986);
   resolved_mc_control_region_ControlRegion_1__18->SetEntries(12);
   resolved_mc_control_region_ControlRegion_1__18->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   resolved_mc_control_region_ControlRegion_1__18->SetFillColor(ci);
   resolved_mc_control_region_ControlRegion_1__18->SetLineWidth(2);
   resolved_mc_control_region_ControlRegion_1__18->GetXaxis()->SetLabelFont(42);
   resolved_mc_control_region_ControlRegion_1__18->GetXaxis()->SetLabelSize(0.035);
   resolved_mc_control_region_ControlRegion_1__18->GetXaxis()->SetTitleSize(0.035);
   resolved_mc_control_region_ControlRegion_1__18->GetXaxis()->SetTitleFont(42);
   resolved_mc_control_region_ControlRegion_1__18->GetYaxis()->SetTitle("Events/GeV");
   resolved_mc_control_region_ControlRegion_1__18->GetYaxis()->SetLabelFont(42);
   resolved_mc_control_region_ControlRegion_1__18->GetYaxis()->SetLabelSize(0.035);
   resolved_mc_control_region_ControlRegion_1__18->GetYaxis()->SetTitleSize(0.035);
   resolved_mc_control_region_ControlRegion_1__18->GetYaxis()->SetTitleFont(42);
   resolved_mc_control_region_ControlRegion_1__18->GetZaxis()->SetLabelFont(42);
   resolved_mc_control_region_ControlRegion_1__18->GetZaxis()->SetLabelSize(0.035);
   resolved_mc_control_region_ControlRegion_1__18->GetZaxis()->SetTitleSize(0.035);
   resolved_mc_control_region_ControlRegion_1__18->GetZaxis()->SetTitleFont(42);
   resolved_mc_control_region_ControlRegion_1__18->Draw("samehist");
   Double_t xAxis19[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_data_control_region_ControlRegion_1__19 = new TH1F("resolved_data_control_region_ControlRegion_1__19","",6, xAxis19);
   resolved_data_control_region_ControlRegion_1__19->SetBinContent(1,0.9);
   resolved_data_control_region_ControlRegion_1__19->SetBinContent(2,0.34);
   resolved_data_control_region_ControlRegion_1__19->SetBinContent(3,0.04);
   resolved_data_control_region_ControlRegion_1__19->SetBinContent(4,0.02);
   resolved_data_control_region_ControlRegion_1__19->SetBinContent(6,0.002);
   resolved_data_control_region_ControlRegion_1__19->SetBinError(1,0.1341641);
   resolved_data_control_region_ControlRegion_1__19->SetBinError(2,0.08246211);
   resolved_data_control_region_ControlRegion_1__19->SetBinError(3,0.02828427);
   resolved_data_control_region_ControlRegion_1__19->SetBinError(4,0.02);
   resolved_data_control_region_ControlRegion_1__19->SetBinError(6,0.002);
   resolved_data_control_region_ControlRegion_1__19->SetEntries(12);
   resolved_data_control_region_ControlRegion_1__19->SetDirectory(0);
   resolved_data_control_region_ControlRegion_1__19->SetLineWidth(2);
   resolved_data_control_region_ControlRegion_1__19->SetMarkerStyle(20);
   resolved_data_control_region_ControlRegion_1__19->GetXaxis()->SetTitle("fake MET (GeV)");
   resolved_data_control_region_ControlRegion_1__19->GetXaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__19->GetXaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_1__19->GetXaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_1__19->GetXaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__19->GetYaxis()->SetTitle("Events/GeV");
   resolved_data_control_region_ControlRegion_1__19->GetYaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__19->GetYaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_1__19->GetYaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_1__19->GetYaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__19->GetZaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__19->GetZaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_1__19->GetZaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_1__19->GetZaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__19->Draw("Pesame");
   
   TLegend *leg = new TLegend(0.54,0.53,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("resolved_data_control_region_ControlRegion_1","Data - Dimuon","PEL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("resolved_control_region_ControlRegion_1","Expected (post-fit)","FL");

   ci = TColor::GetColor("#ccccff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("resolved_mc_control_region_ControlRegion_1","Backgrounds Component","F");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("control_region_ControlRegion_1","Expected (pre-fit)","L");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.1,0.92,"#bf{CMS} #it{Preliminary}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
   Double_t xAxis20[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_data_control_region_ControlRegion_1__20 = new TH1F("resolved_data_control_region_ControlRegion_1__20","",6, xAxis20);
   resolved_data_control_region_ControlRegion_1__20->SetBinContent(1,0.9);
   resolved_data_control_region_ControlRegion_1__20->SetBinContent(2,0.34);
   resolved_data_control_region_ControlRegion_1__20->SetBinContent(3,0.04);
   resolved_data_control_region_ControlRegion_1__20->SetBinContent(4,0.02);
   resolved_data_control_region_ControlRegion_1__20->SetBinContent(6,0.002);
   resolved_data_control_region_ControlRegion_1__20->SetBinError(1,0.1341641);
   resolved_data_control_region_ControlRegion_1__20->SetBinError(2,0.08246211);
   resolved_data_control_region_ControlRegion_1__20->SetBinError(3,0.02828427);
   resolved_data_control_region_ControlRegion_1__20->SetBinError(4,0.02);
   resolved_data_control_region_ControlRegion_1__20->SetBinError(6,0.002);
   resolved_data_control_region_ControlRegion_1__20->SetEntries(12);
   resolved_data_control_region_ControlRegion_1__20->SetDirectory(0);
   resolved_data_control_region_ControlRegion_1__20->SetLineWidth(2);
   resolved_data_control_region_ControlRegion_1__20->SetMarkerStyle(20);
   resolved_data_control_region_ControlRegion_1__20->GetXaxis()->SetTitle("fake MET (GeV)");
   resolved_data_control_region_ControlRegion_1__20->GetXaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__20->GetXaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_1__20->GetXaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_1__20->GetXaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__20->GetYaxis()->SetTitle("Events/GeV");
   resolved_data_control_region_ControlRegion_1__20->GetYaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__20->GetYaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_1__20->GetYaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_1__20->GetYaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__20->GetZaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__20->GetZaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_1__20->GetZaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_1__20->GetZaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__20->Draw("sameaxis");
   p1->Modified();
   c_ControlRegion_1->cd();
  
// ------------>Primitives in pad: p2
   p2 = new TPad("p2", "p2",0,0.068,1,0.285);
   p2->Draw();
   p2->cd();
   p2->Range(156.25,0.02627906,1093.75,1.863488);
   p2->SetFillColor(0);
   p2->SetBorderMode(0);
   p2->SetBorderSize(2);
   p2->SetTopMargin(0.04);
   p2->SetFrameBorderMode(0);
   p2->SetFrameBorderMode(0);
   Double_t xAxis21[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_data_control_region_ControlRegion_1__21 = new TH1F("resolved_data_control_region_ControlRegion_1__21","",6, xAxis21);
   resolved_data_control_region_ControlRegion_1__21->SetBinContent(1,1.053773);
   resolved_data_control_region_ControlRegion_1__21->SetBinContent(2,1.095122);
   resolved_data_control_region_ControlRegion_1__21->SetBinContent(3,0.4493797);
   resolved_data_control_region_ControlRegion_1__21->SetBinContent(4,0.4268424);
   resolved_data_control_region_ControlRegion_1__21->SetBinContent(6,0.7642936);
   resolved_data_control_region_ControlRegion_1__21->SetBinError(1,0.1570872);
   resolved_data_control_region_ControlRegion_1__21->SetBinError(2,0.2656062);
   resolved_data_control_region_ControlRegion_1__21->SetBinError(3,0.3177594);
   resolved_data_control_region_ControlRegion_1__21->SetBinError(4,0.4268424);
   resolved_data_control_region_ControlRegion_1__21->SetBinError(6,0.7642936);
   resolved_data_control_region_ControlRegion_1__21->SetMinimum(0.21);
   resolved_data_control_region_ControlRegion_1__21->SetMaximum(1.79);
   resolved_data_control_region_ControlRegion_1__21->SetEntries(14.91859);
   resolved_data_control_region_ControlRegion_1__21->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   resolved_data_control_region_ControlRegion_1__21->SetLineColor(ci);
   resolved_data_control_region_ControlRegion_1__21->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   resolved_data_control_region_ControlRegion_1__21->SetMarkerColor(ci);
   resolved_data_control_region_ControlRegion_1__21->SetMarkerStyle(20);
   resolved_data_control_region_ControlRegion_1__21->GetXaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__21->GetXaxis()->SetLabelSize(0.12);
   resolved_data_control_region_ControlRegion_1__21->GetXaxis()->SetTitleSize(0.085);
   resolved_data_control_region_ControlRegion_1__21->GetXaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__21->GetYaxis()->SetTitle("Data/Bkg");
   resolved_data_control_region_ControlRegion_1__21->GetYaxis()->SetNdivisions(5);
   resolved_data_control_region_ControlRegion_1__21->GetYaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__21->GetYaxis()->SetLabelSize(0.1);
   resolved_data_control_region_ControlRegion_1__21->GetYaxis()->SetTitleSize(0.12);
   resolved_data_control_region_ControlRegion_1__21->GetYaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__21->GetZaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__21->GetZaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_1__21->GetZaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_1__21->GetZaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__21->Draw("");
   Double_t xAxis22[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *OneWithError_resolved_data_control_region_ControlRegion_1__22 = new TH1F("OneWithError_resolved_data_control_region_ControlRegion_1__22","",6, xAxis22);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetBinContent(1,1);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetBinContent(2,1);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetBinContent(3,1);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetBinContent(4,1);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetBinContent(5,1);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetBinContent(6,1);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetBinError(1,0.0727369);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetBinError(2,0.1134362);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetBinError(3,0.2019469);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetBinError(4,0.3237779);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetBinError(5,0.396738);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetBinError(6,0.5540659);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetMinimum(0.21);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetMaximum(1.79);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetEntries(20.91859);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetDirectory(0);

   ci = TColor::GetColor("#ccccff");
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetFillColor(ci);

   ci = TColor::GetColor("#ccccff");
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetLineColor(ci);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetMarkerColor(ci);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetMarkerStyle(20);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->SetMarkerSize(0);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->GetXaxis()->SetLabelFont(42);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->GetXaxis()->SetLabelSize(0.12);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->GetXaxis()->SetTitleSize(0.085);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->GetXaxis()->SetTitleFont(42);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->GetYaxis()->SetTitle("Data/Bkg");
   OneWithError_resolved_data_control_region_ControlRegion_1__22->GetYaxis()->SetNdivisions(5);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->GetYaxis()->SetLabelFont(42);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->GetYaxis()->SetLabelSize(0.1);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->GetYaxis()->SetTitleSize(0.12);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->GetYaxis()->SetTitleFont(42);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->GetZaxis()->SetLabelFont(42);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->GetZaxis()->SetLabelSize(0.035);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->GetZaxis()->SetTitleSize(0.035);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->GetZaxis()->SetTitleFont(42);
   OneWithError_resolved_data_control_region_ControlRegion_1__22->Draw("sameE2");
   TLine *line = new TLine(250,1,1000,1);
   line->SetLineStyle(2);
   line->SetLineWidth(2);
   line->Draw();
   Double_t xAxis23[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_data_control_region_ControlRegion_1__23 = new TH1F("resolved_data_control_region_ControlRegion_1__23","",6, xAxis23);
   resolved_data_control_region_ControlRegion_1__23->SetBinContent(1,1.053773);
   resolved_data_control_region_ControlRegion_1__23->SetBinContent(2,1.095122);
   resolved_data_control_region_ControlRegion_1__23->SetBinContent(3,0.4493797);
   resolved_data_control_region_ControlRegion_1__23->SetBinContent(4,0.4268424);
   resolved_data_control_region_ControlRegion_1__23->SetBinContent(6,0.7642936);
   resolved_data_control_region_ControlRegion_1__23->SetBinError(1,0.1570872);
   resolved_data_control_region_ControlRegion_1__23->SetBinError(2,0.2656062);
   resolved_data_control_region_ControlRegion_1__23->SetBinError(3,0.3177594);
   resolved_data_control_region_ControlRegion_1__23->SetBinError(4,0.4268424);
   resolved_data_control_region_ControlRegion_1__23->SetBinError(6,0.7642936);
   resolved_data_control_region_ControlRegion_1__23->SetMinimum(0.21);
   resolved_data_control_region_ControlRegion_1__23->SetMaximum(1.79);
   resolved_data_control_region_ControlRegion_1__23->SetEntries(14.91859);
   resolved_data_control_region_ControlRegion_1__23->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   resolved_data_control_region_ControlRegion_1__23->SetLineColor(ci);
   resolved_data_control_region_ControlRegion_1__23->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   resolved_data_control_region_ControlRegion_1__23->SetMarkerColor(ci);
   resolved_data_control_region_ControlRegion_1__23->SetMarkerStyle(20);
   resolved_data_control_region_ControlRegion_1__23->GetXaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__23->GetXaxis()->SetLabelSize(0.12);
   resolved_data_control_region_ControlRegion_1__23->GetXaxis()->SetTitleSize(0.085);
   resolved_data_control_region_ControlRegion_1__23->GetXaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__23->GetYaxis()->SetTitle("Data/Bkg");
   resolved_data_control_region_ControlRegion_1__23->GetYaxis()->SetNdivisions(5);
   resolved_data_control_region_ControlRegion_1__23->GetYaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__23->GetYaxis()->SetLabelSize(0.1);
   resolved_data_control_region_ControlRegion_1__23->GetYaxis()->SetTitleSize(0.12);
   resolved_data_control_region_ControlRegion_1__23->GetYaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__23->GetZaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__23->GetZaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_1__23->GetZaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_1__23->GetZaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__23->Draw("same");
   Double_t xAxis24[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_data_control_region_ControlRegion_1__24 = new TH1F("resolved_data_control_region_ControlRegion_1__24","",6, xAxis24);
   resolved_data_control_region_ControlRegion_1__24->SetBinContent(1,1.284544);
   resolved_data_control_region_ControlRegion_1__24->SetBinContent(2,1.405121);
   resolved_data_control_region_ControlRegion_1__24->SetBinContent(3,0.4749693);
   resolved_data_control_region_ControlRegion_1__24->SetBinContent(4,0.5861446);
   resolved_data_control_region_ControlRegion_1__24->SetBinContent(6,0.908843);
   resolved_data_control_region_ControlRegion_1__24->SetBinError(1,0.1914886);
   resolved_data_control_region_ControlRegion_1__24->SetBinError(2,0.340792);
   resolved_data_control_region_ControlRegion_1__24->SetBinError(3,0.335854);
   resolved_data_control_region_ControlRegion_1__24->SetBinError(4,0.5861446);
   resolved_data_control_region_ControlRegion_1__24->SetBinError(6,0.9088429);
   resolved_data_control_region_ControlRegion_1__24->SetEntries(15.12862);
   resolved_data_control_region_ControlRegion_1__24->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   resolved_data_control_region_ControlRegion_1__24->SetLineColor(ci);
   resolved_data_control_region_ControlRegion_1__24->SetLineWidth(2);

   ci = TColor::GetColor("#ff0000");
   resolved_data_control_region_ControlRegion_1__24->SetMarkerColor(ci);
   resolved_data_control_region_ControlRegion_1__24->SetMarkerStyle(20);
   resolved_data_control_region_ControlRegion_1__24->GetXaxis()->SetTitle("fake MET (GeV)");
   resolved_data_control_region_ControlRegion_1__24->GetXaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__24->GetXaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_1__24->GetXaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_1__24->GetXaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__24->GetYaxis()->SetTitle("Events/GeV");
   resolved_data_control_region_ControlRegion_1__24->GetYaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__24->GetYaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_1__24->GetYaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_1__24->GetYaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__24->GetZaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__24->GetZaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_1__24->GetZaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_1__24->GetZaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__24->Draw("pelsame");
   Double_t xAxis25[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_data_control_region_ControlRegion_1__25 = new TH1F("resolved_data_control_region_ControlRegion_1__25","",6, xAxis25);
   resolved_data_control_region_ControlRegion_1__25->SetBinContent(1,1.053773);
   resolved_data_control_region_ControlRegion_1__25->SetBinContent(2,1.095122);
   resolved_data_control_region_ControlRegion_1__25->SetBinContent(3,0.4493797);
   resolved_data_control_region_ControlRegion_1__25->SetBinContent(4,0.4268424);
   resolved_data_control_region_ControlRegion_1__25->SetBinContent(6,0.7642936);
   resolved_data_control_region_ControlRegion_1__25->SetBinError(1,0.1570872);
   resolved_data_control_region_ControlRegion_1__25->SetBinError(2,0.2656062);
   resolved_data_control_region_ControlRegion_1__25->SetBinError(3,0.3177594);
   resolved_data_control_region_ControlRegion_1__25->SetBinError(4,0.4268424);
   resolved_data_control_region_ControlRegion_1__25->SetBinError(6,0.7642936);
   resolved_data_control_region_ControlRegion_1__25->SetMinimum(0.21);
   resolved_data_control_region_ControlRegion_1__25->SetMaximum(1.79);
   resolved_data_control_region_ControlRegion_1__25->SetEntries(14.91859);
   resolved_data_control_region_ControlRegion_1__25->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   resolved_data_control_region_ControlRegion_1__25->SetLineColor(ci);
   resolved_data_control_region_ControlRegion_1__25->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   resolved_data_control_region_ControlRegion_1__25->SetMarkerColor(ci);
   resolved_data_control_region_ControlRegion_1__25->SetMarkerStyle(20);
   resolved_data_control_region_ControlRegion_1__25->GetXaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__25->GetXaxis()->SetLabelSize(0.12);
   resolved_data_control_region_ControlRegion_1__25->GetXaxis()->SetTitleSize(0.085);
   resolved_data_control_region_ControlRegion_1__25->GetXaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__25->GetYaxis()->SetTitle("Data/Bkg");
   resolved_data_control_region_ControlRegion_1__25->GetYaxis()->SetNdivisions(5);
   resolved_data_control_region_ControlRegion_1__25->GetYaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__25->GetYaxis()->SetLabelSize(0.1);
   resolved_data_control_region_ControlRegion_1__25->GetYaxis()->SetTitleSize(0.12);
   resolved_data_control_region_ControlRegion_1__25->GetYaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__25->GetZaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__25->GetZaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_1__25->GetZaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_1__25->GetZaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__25->Draw("samepel");
   Double_t xAxis26[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *resolved_data_control_region_ControlRegion_1__26 = new TH1F("resolved_data_control_region_ControlRegion_1__26","",6, xAxis26);
   resolved_data_control_region_ControlRegion_1__26->SetBinContent(1,1.053773);
   resolved_data_control_region_ControlRegion_1__26->SetBinContent(2,1.095122);
   resolved_data_control_region_ControlRegion_1__26->SetBinContent(3,0.4493797);
   resolved_data_control_region_ControlRegion_1__26->SetBinContent(4,0.4268424);
   resolved_data_control_region_ControlRegion_1__26->SetBinContent(6,0.7642936);
   resolved_data_control_region_ControlRegion_1__26->SetBinError(1,0.1570872);
   resolved_data_control_region_ControlRegion_1__26->SetBinError(2,0.2656062);
   resolved_data_control_region_ControlRegion_1__26->SetBinError(3,0.3177594);
   resolved_data_control_region_ControlRegion_1__26->SetBinError(4,0.4268424);
   resolved_data_control_region_ControlRegion_1__26->SetBinError(6,0.7642936);
   resolved_data_control_region_ControlRegion_1__26->SetMinimum(0.21);
   resolved_data_control_region_ControlRegion_1__26->SetMaximum(1.79);
   resolved_data_control_region_ControlRegion_1__26->SetEntries(14.91859);
   resolved_data_control_region_ControlRegion_1__26->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   resolved_data_control_region_ControlRegion_1__26->SetLineColor(ci);
   resolved_data_control_region_ControlRegion_1__26->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   resolved_data_control_region_ControlRegion_1__26->SetMarkerColor(ci);
   resolved_data_control_region_ControlRegion_1__26->SetMarkerStyle(20);
   resolved_data_control_region_ControlRegion_1__26->GetXaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__26->GetXaxis()->SetLabelSize(0.12);
   resolved_data_control_region_ControlRegion_1__26->GetXaxis()->SetTitleSize(0.085);
   resolved_data_control_region_ControlRegion_1__26->GetXaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__26->GetYaxis()->SetTitle("Data/Bkg");
   resolved_data_control_region_ControlRegion_1__26->GetYaxis()->SetNdivisions(5);
   resolved_data_control_region_ControlRegion_1__26->GetYaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__26->GetYaxis()->SetLabelSize(0.1);
   resolved_data_control_region_ControlRegion_1__26->GetYaxis()->SetTitleSize(0.12);
   resolved_data_control_region_ControlRegion_1__26->GetYaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__26->GetZaxis()->SetLabelFont(42);
   resolved_data_control_region_ControlRegion_1__26->GetZaxis()->SetLabelSize(0.035);
   resolved_data_control_region_ControlRegion_1__26->GetZaxis()->SetTitleSize(0.035);
   resolved_data_control_region_ControlRegion_1__26->GetZaxis()->SetTitleFont(42);
   resolved_data_control_region_ControlRegion_1__26->Draw("sameaxis");
   p2->Modified();
   c_ControlRegion_1->cd();
      tex = new TLatex(0.7,0.94,"resolved category");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.7,0.03,"fake MET (GeV)");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   c_ControlRegion_1->Modified();
   c_ControlRegion_1->cd();
   c_ControlRegion_1->SetSelected(c_ControlRegion_1);
}
