{
//=========Macro generated from canvas: c_ControlRegion_0/
//=========  (Sun Jun 21 12:53:05 2015) by ROOT version5.34/18
   TCanvas *c_ControlRegion_0 = new TCanvas("c_ControlRegion_0", "",0,0,800,800);
   gStyle->SetOptStat(0);
   c_ControlRegion_0->SetHighLightColor(2);
   c_ControlRegion_0->Range(0,0,1,1);
   c_ControlRegion_0->SetFillColor(0);
   c_ControlRegion_0->SetBorderMode(0);
   c_ControlRegion_0->SetBorderSize(2);
   c_ControlRegion_0->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: p1
   TPad *p1 = new TPad("p1", "p1",0,0.28,1,1);
   p1->Draw();
   p1->cd();
   p1->Range(156.25,-1.035287,1093.75,2.280887);
   p1->SetFillColor(0);
   p1->SetBorderMode(0);
   p1->SetBorderSize(2);
   p1->SetLogy();
   p1->SetBottomMargin(0.01);
   p1->SetFrameBorderMode(0);
   p1->SetFrameBorderMode(0);
   Double_t xAxis1[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_data_control_region_ControlRegion_0__1 = new TH1F("boosted_data_control_region_ControlRegion_0__1","",6, xAxis1);
   boosted_data_control_region_ControlRegion_0__1->SetMinimum(0.02);
   boosted_data_control_region_ControlRegion_0__1->SetBinContent(1,46);
   boosted_data_control_region_ControlRegion_0__1->SetBinContent(2,18.86);
   boosted_data_control_region_ControlRegion_0__1->SetBinContent(3,8.06);
   boosted_data_control_region_ControlRegion_0__1->SetBinContent(4,3.5);
   boosted_data_control_region_ControlRegion_0__1->SetBinContent(5,1.84);
   boosted_data_control_region_ControlRegion_0__1->SetBinContent(6,0.22);
   boosted_data_control_region_ControlRegion_0__1->SetBinError(1,0.9591663);
   boosted_data_control_region_ControlRegion_0__1->SetBinError(2,0.6141661);
   boosted_data_control_region_ControlRegion_0__1->SetBinError(3,0.4014972);
   boosted_data_control_region_ControlRegion_0__1->SetBinError(4,0.2645751);
   boosted_data_control_region_ControlRegion_0__1->SetBinError(5,0.1918333);
   boosted_data_control_region_ControlRegion_0__1->SetBinError(6,0.02097618);
   boosted_data_control_region_ControlRegion_0__1->SetEntries(12);
   boosted_data_control_region_ControlRegion_0__1->SetDirectory(0);
   boosted_data_control_region_ControlRegion_0__1->SetLineWidth(2);
   boosted_data_control_region_ControlRegion_0__1->SetMarkerStyle(20);
   boosted_data_control_region_ControlRegion_0__1->GetXaxis()->SetTitle("fake MET (GeV)");
   boosted_data_control_region_ControlRegion_0__1->GetXaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__1->GetXaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_0__1->GetXaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_0__1->GetXaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__1->GetYaxis()->SetTitle("Events/GeV");
   boosted_data_control_region_ControlRegion_0__1->GetYaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__1->GetYaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_0__1->GetYaxis()->SetTitleSize(0.05);
   boosted_data_control_region_ControlRegion_0__1->GetYaxis()->SetTitleOffset(0.8);
   boosted_data_control_region_ControlRegion_0__1->GetYaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__1->GetZaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__1->GetZaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_0__1->GetZaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_0__1->GetZaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__1->Draw("Pe");
   Double_t xAxis2[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_control_region_ControlRegion_0__2 = new TH1F("boosted_control_region_ControlRegion_0__2","Expected ControlRegion_0 control region",6, xAxis2);
   boosted_control_region_ControlRegion_0__2->SetBinContent(1,45.75837);
   boosted_control_region_ControlRegion_0__2->SetBinContent(2,18.6848);
   boosted_control_region_ControlRegion_0__2->SetBinContent(3,8.173073);
   boosted_control_region_ControlRegion_0__2->SetBinContent(4,3.539049);
   boosted_control_region_ControlRegion_0__2->SetBinContent(5,1.880406);
   boosted_control_region_ControlRegion_0__2->SetBinContent(6,0.2222698);
   boosted_control_region_ControlRegion_0__2->SetBinError(1,0.9453037);
   boosted_control_region_ControlRegion_0__2->SetBinError(2,0.6033372);
   boosted_control_region_ControlRegion_0__2->SetBinError(3,0.4107515);
   boosted_control_region_ControlRegion_0__2->SetBinError(4,0.2449745);
   boosted_control_region_ControlRegion_0__2->SetBinError(5,0.1951376);
   boosted_control_region_ControlRegion_0__2->SetBinError(6,0.0231193);
   boosted_control_region_ControlRegion_0__2->SetEntries(12);
   boosted_control_region_ControlRegion_0__2->SetDirectory(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#ccccff");
   boosted_control_region_ControlRegion_0__2->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   boosted_control_region_ControlRegion_0__2->SetLineColor(ci);
   boosted_control_region_ControlRegion_0__2->SetLineWidth(2);
   boosted_control_region_ControlRegion_0__2->GetXaxis()->SetLabelFont(42);
   boosted_control_region_ControlRegion_0__2->GetXaxis()->SetLabelSize(0.035);
   boosted_control_region_ControlRegion_0__2->GetXaxis()->SetTitleSize(0.035);
   boosted_control_region_ControlRegion_0__2->GetXaxis()->SetTitleFont(42);
   boosted_control_region_ControlRegion_0__2->GetYaxis()->SetTitle("Events/GeV");
   boosted_control_region_ControlRegion_0__2->GetYaxis()->SetLabelFont(42);
   boosted_control_region_ControlRegion_0__2->GetYaxis()->SetLabelSize(0.035);
   boosted_control_region_ControlRegion_0__2->GetYaxis()->SetTitleSize(0.035);
   boosted_control_region_ControlRegion_0__2->GetYaxis()->SetTitleFont(42);
   boosted_control_region_ControlRegion_0__2->GetZaxis()->SetLabelFont(42);
   boosted_control_region_ControlRegion_0__2->GetZaxis()->SetLabelSize(0.035);
   boosted_control_region_ControlRegion_0__2->GetZaxis()->SetTitleSize(0.035);
   boosted_control_region_ControlRegion_0__2->GetZaxis()->SetTitleFont(42);
   boosted_control_region_ControlRegion_0__2->Draw("sameE2");
   Double_t xAxis3[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *control_region_ControlRegion_0__3 = new TH1F("control_region_ControlRegion_0__3","Expected ControlRegion_0 control region",6, xAxis3);
   control_region_ControlRegion_0__3->SetBinContent(1,39.66823);
   control_region_ControlRegion_0__3->SetBinContent(2,17.79908);
   control_region_ControlRegion_0__3->SetBinContent(3,8.452147);
   control_region_ControlRegion_0__3->SetBinContent(4,4.161262);
   control_region_ControlRegion_0__3->SetBinContent(5,2.12417);
   control_region_ControlRegion_0__3->SetBinContent(6,0.1870747);
   control_region_ControlRegion_0__3->SetEntries(12);
   control_region_ControlRegion_0__3->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   control_region_ControlRegion_0__3->SetLineColor(ci);
   control_region_ControlRegion_0__3->SetLineWidth(2);
   control_region_ControlRegion_0__3->GetXaxis()->SetLabelFont(42);
   control_region_ControlRegion_0__3->GetXaxis()->SetLabelSize(0.035);
   control_region_ControlRegion_0__3->GetXaxis()->SetTitleSize(0.035);
   control_region_ControlRegion_0__3->GetXaxis()->SetTitleFont(42);
   control_region_ControlRegion_0__3->GetYaxis()->SetTitle("Events/GeV");
   control_region_ControlRegion_0__3->GetYaxis()->SetLabelFont(42);
   control_region_ControlRegion_0__3->GetYaxis()->SetLabelSize(0.035);
   control_region_ControlRegion_0__3->GetYaxis()->SetTitleSize(0.035);
   control_region_ControlRegion_0__3->GetYaxis()->SetTitleFont(42);
   control_region_ControlRegion_0__3->GetZaxis()->SetLabelFont(42);
   control_region_ControlRegion_0__3->GetZaxis()->SetLabelSize(0.035);
   control_region_ControlRegion_0__3->GetZaxis()->SetTitleSize(0.035);
   control_region_ControlRegion_0__3->GetZaxis()->SetTitleFont(42);
   control_region_ControlRegion_0__3->Draw("samehist");
   Double_t xAxis4[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_control_region_ControlRegion_0__4 = new TH1F("boosted_control_region_ControlRegion_0__4","Expected ControlRegion_0 control region",6, xAxis4);
   boosted_control_region_ControlRegion_0__4->SetBinContent(1,45.75837);
   boosted_control_region_ControlRegion_0__4->SetBinContent(2,18.6848);
   boosted_control_region_ControlRegion_0__4->SetBinContent(3,8.173073);
   boosted_control_region_ControlRegion_0__4->SetBinContent(4,3.539049);
   boosted_control_region_ControlRegion_0__4->SetBinContent(5,1.880406);
   boosted_control_region_ControlRegion_0__4->SetBinContent(6,0.2222698);
   boosted_control_region_ControlRegion_0__4->SetBinError(1,0.9453037);
   boosted_control_region_ControlRegion_0__4->SetBinError(2,0.6033372);
   boosted_control_region_ControlRegion_0__4->SetBinError(3,0.4107515);
   boosted_control_region_ControlRegion_0__4->SetBinError(4,0.2449745);
   boosted_control_region_ControlRegion_0__4->SetBinError(5,0.1951376);
   boosted_control_region_ControlRegion_0__4->SetBinError(6,0.0231193);
   boosted_control_region_ControlRegion_0__4->SetEntries(12);
   boosted_control_region_ControlRegion_0__4->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   boosted_control_region_ControlRegion_0__4->SetLineColor(ci);
   boosted_control_region_ControlRegion_0__4->SetLineWidth(2);
   boosted_control_region_ControlRegion_0__4->GetXaxis()->SetLabelFont(42);
   boosted_control_region_ControlRegion_0__4->GetXaxis()->SetLabelSize(0.035);
   boosted_control_region_ControlRegion_0__4->GetXaxis()->SetTitleSize(0.035);
   boosted_control_region_ControlRegion_0__4->GetXaxis()->SetTitleFont(42);
   boosted_control_region_ControlRegion_0__4->GetYaxis()->SetTitle("Events/GeV");
   boosted_control_region_ControlRegion_0__4->GetYaxis()->SetLabelFont(42);
   boosted_control_region_ControlRegion_0__4->GetYaxis()->SetLabelSize(0.035);
   boosted_control_region_ControlRegion_0__4->GetYaxis()->SetTitleSize(0.035);
   boosted_control_region_ControlRegion_0__4->GetYaxis()->SetTitleFont(42);
   boosted_control_region_ControlRegion_0__4->GetZaxis()->SetLabelFont(42);
   boosted_control_region_ControlRegion_0__4->GetZaxis()->SetLabelSize(0.035);
   boosted_control_region_ControlRegion_0__4->GetZaxis()->SetTitleSize(0.035);
   boosted_control_region_ControlRegion_0__4->GetZaxis()->SetTitleFont(42);
   boosted_control_region_ControlRegion_0__4->Draw("histsame");
   Double_t xAxis5[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_mc_control_region_ControlRegion_0__5 = new TH1F("boosted_mc_control_region_ControlRegion_0__5","Background ControlRegion_0 control region",6, xAxis5);
   boosted_mc_control_region_ControlRegion_0__5->SetBinContent(1,1.393036);
   boosted_mc_control_region_ControlRegion_0__5->SetBinContent(2,0.4841732);
   boosted_mc_control_region_ControlRegion_0__5->SetBinContent(3,0.1985777);
   boosted_mc_control_region_ControlRegion_0__5->SetBinContent(4,0.08879171);
   boosted_mc_control_region_ControlRegion_0__5->SetBinContent(5,0.04677502);
   boosted_mc_control_region_ControlRegion_0__5->SetBinContent(6,0.005600584);
   boosted_mc_control_region_ControlRegion_0__5->SetBinError(1,0.1669153);
   boosted_mc_control_region_ControlRegion_0__5->SetBinError(2,0.0984046);
   boosted_mc_control_region_ControlRegion_0__5->SetBinError(3,0.06302027);
   boosted_mc_control_region_ControlRegion_0__5->SetBinError(4,0.04214065);
   boosted_mc_control_region_ControlRegion_0__5->SetBinError(5,0.03058595);
   boosted_mc_control_region_ControlRegion_0__5->SetBinError(6,0.003346815);
   boosted_mc_control_region_ControlRegion_0__5->SetEntries(12);
   boosted_mc_control_region_ControlRegion_0__5->SetDirectory(0);

   ci = TColor::GetColor("#cccccc");
   boosted_mc_control_region_ControlRegion_0__5->SetFillColor(ci);
   boosted_mc_control_region_ControlRegion_0__5->SetLineWidth(2);
   boosted_mc_control_region_ControlRegion_0__5->GetXaxis()->SetLabelFont(42);
   boosted_mc_control_region_ControlRegion_0__5->GetXaxis()->SetLabelSize(0.035);
   boosted_mc_control_region_ControlRegion_0__5->GetXaxis()->SetTitleSize(0.035);
   boosted_mc_control_region_ControlRegion_0__5->GetXaxis()->SetTitleFont(42);
   boosted_mc_control_region_ControlRegion_0__5->GetYaxis()->SetTitle("Events/GeV");
   boosted_mc_control_region_ControlRegion_0__5->GetYaxis()->SetLabelFont(42);
   boosted_mc_control_region_ControlRegion_0__5->GetYaxis()->SetLabelSize(0.035);
   boosted_mc_control_region_ControlRegion_0__5->GetYaxis()->SetTitleSize(0.035);
   boosted_mc_control_region_ControlRegion_0__5->GetYaxis()->SetTitleFont(42);
   boosted_mc_control_region_ControlRegion_0__5->GetZaxis()->SetLabelFont(42);
   boosted_mc_control_region_ControlRegion_0__5->GetZaxis()->SetLabelSize(0.035);
   boosted_mc_control_region_ControlRegion_0__5->GetZaxis()->SetTitleSize(0.035);
   boosted_mc_control_region_ControlRegion_0__5->GetZaxis()->SetTitleFont(42);
   boosted_mc_control_region_ControlRegion_0__5->Draw("samehist");
   Double_t xAxis6[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_data_control_region_ControlRegion_0__6 = new TH1F("boosted_data_control_region_ControlRegion_0__6","",6, xAxis6);
   boosted_data_control_region_ControlRegion_0__6->SetBinContent(1,46);
   boosted_data_control_region_ControlRegion_0__6->SetBinContent(2,18.86);
   boosted_data_control_region_ControlRegion_0__6->SetBinContent(3,8.06);
   boosted_data_control_region_ControlRegion_0__6->SetBinContent(4,3.5);
   boosted_data_control_region_ControlRegion_0__6->SetBinContent(5,1.84);
   boosted_data_control_region_ControlRegion_0__6->SetBinContent(6,0.22);
   boosted_data_control_region_ControlRegion_0__6->SetBinError(1,0.9591663);
   boosted_data_control_region_ControlRegion_0__6->SetBinError(2,0.6141661);
   boosted_data_control_region_ControlRegion_0__6->SetBinError(3,0.4014972);
   boosted_data_control_region_ControlRegion_0__6->SetBinError(4,0.2645751);
   boosted_data_control_region_ControlRegion_0__6->SetBinError(5,0.1918333);
   boosted_data_control_region_ControlRegion_0__6->SetBinError(6,0.02097618);
   boosted_data_control_region_ControlRegion_0__6->SetEntries(12);
   boosted_data_control_region_ControlRegion_0__6->SetDirectory(0);
   boosted_data_control_region_ControlRegion_0__6->SetLineWidth(2);
   boosted_data_control_region_ControlRegion_0__6->SetMarkerStyle(20);
   boosted_data_control_region_ControlRegion_0__6->GetXaxis()->SetTitle("fake MET (GeV)");
   boosted_data_control_region_ControlRegion_0__6->GetXaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__6->GetXaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_0__6->GetXaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_0__6->GetXaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__6->GetYaxis()->SetTitle("Events/GeV");
   boosted_data_control_region_ControlRegion_0__6->GetYaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__6->GetYaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_0__6->GetYaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_0__6->GetYaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__6->GetZaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__6->GetZaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_0__6->GetZaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_0__6->GetZaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__6->Draw("Pesame");
   
   TLegend *leg = new TLegend(0.54,0.53,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("boosted_data_control_region_ControlRegion_0","Data - Photon+jet","PEL");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("boosted_control_region_ControlRegion_0","Expected (post-fit)","FL");

   ci = TColor::GetColor("#ccccff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("boosted_mc_control_region_ControlRegion_0","Backgrounds Component","F");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("control_region_ControlRegion_0","Expected (pre-fit)","L");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.2,0.8,"#bf{CMS}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.07);
   tex->SetLineWidth(2);
   tex->Draw();
   tex = new TLatex(0.1,0.92,"boosted category");
   tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
   tex->DrawLatex(0.7,0.92,"19.7 fb^{-1} (8TeV)");
   //tex->DrawLatex(0.1,0.92,"boosted category");
   Double_t xAxis7[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_data_control_region_ControlRegion_0__7 = new TH1F("boosted_data_control_region_ControlRegion_0__7","",6, xAxis7);
   boosted_data_control_region_ControlRegion_0__7->SetBinContent(1,46);
   boosted_data_control_region_ControlRegion_0__7->SetBinContent(2,18.86);
   boosted_data_control_region_ControlRegion_0__7->SetBinContent(3,8.06);
   boosted_data_control_region_ControlRegion_0__7->SetBinContent(4,3.5);
   boosted_data_control_region_ControlRegion_0__7->SetBinContent(5,1.84);
   boosted_data_control_region_ControlRegion_0__7->SetBinContent(6,0.22);
   boosted_data_control_region_ControlRegion_0__7->SetBinError(1,0.9591663);
   boosted_data_control_region_ControlRegion_0__7->SetBinError(2,0.6141661);
   boosted_data_control_region_ControlRegion_0__7->SetBinError(3,0.4014972);
   boosted_data_control_region_ControlRegion_0__7->SetBinError(4,0.2645751);
   boosted_data_control_region_ControlRegion_0__7->SetBinError(5,0.1918333);
   boosted_data_control_region_ControlRegion_0__7->SetBinError(6,0.02097618);
   boosted_data_control_region_ControlRegion_0__7->SetEntries(12);
   boosted_data_control_region_ControlRegion_0__7->SetDirectory(0);
   boosted_data_control_region_ControlRegion_0__7->SetLineWidth(2);
   boosted_data_control_region_ControlRegion_0__7->SetMarkerStyle(20);
   boosted_data_control_region_ControlRegion_0__7->GetXaxis()->SetTitle("fake MET (GeV)");
   boosted_data_control_region_ControlRegion_0__7->GetXaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__7->GetXaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_0__7->GetXaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_0__7->GetXaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__7->GetYaxis()->SetTitle("Events/GeV");
   boosted_data_control_region_ControlRegion_0__7->GetYaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__7->GetYaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_0__7->GetYaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_0__7->GetYaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__7->GetZaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__7->GetZaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_0__7->GetZaxis()->SetTitleSize(0.5);
   boosted_data_control_region_ControlRegion_0__7->GetZaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__7->Draw("sameaxis");
   p1->Modified();
   c_ControlRegion_0->cd();
  
// ------------>Primitives in pad: p2
   p2 = new TPad("p2", "p2",0,0.068,1,0.285);
   p2->Draw();
   p2->cd();
   p2->Range(156.25,0.02627906,1093.75,1.863488);
   p2->SetFillColor(0);
   p2->SetBorderMode(0);
   p2->SetBorderSize(2);
   p2->SetTopMargin(0.04);
   p2->SetFrameBorderMode(0);
   p2->SetFrameBorderMode(0);
   Double_t xAxis8[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_data_control_region_ControlRegion_0__8 = new TH1F("boosted_data_control_region_ControlRegion_0__8","",6, xAxis8);
   boosted_data_control_region_ControlRegion_0__8->SetBinContent(1,1.005281);
   boosted_data_control_region_ControlRegion_0__8->SetBinContent(2,1.009377);
   boosted_data_control_region_ControlRegion_0__8->SetBinContent(3,0.9861652);
   boosted_data_control_region_ControlRegion_0__8->SetBinContent(4,0.9889661);
   boosted_data_control_region_ControlRegion_0__8->SetBinContent(5,0.978512);
   boosted_data_control_region_ControlRegion_0__8->SetBinContent(6,0.9897881);
   boosted_data_control_region_ControlRegion_0__8->SetBinError(1,0.02096155);
   boosted_data_control_region_ControlRegion_0__8->SetBinError(2,0.03286983);
   boosted_data_control_region_ControlRegion_0__8->SetBinError(3,0.04912439);
   boosted_data_control_region_ControlRegion_0__8->SetBinError(4,0.07475881);
   boosted_data_control_region_ControlRegion_0__8->SetBinError(5,0.1020169);
   boosted_data_control_region_ControlRegion_0__8->SetBinError(6,0.0943726);
   boosted_data_control_region_ControlRegion_0__8->SetMinimum(0.21);
   boosted_data_control_region_ControlRegion_0__8->SetMaximum(1.79);
   boosted_data_control_region_ControlRegion_0__8->SetEntries(1231.079);
   boosted_data_control_region_ControlRegion_0__8->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   boosted_data_control_region_ControlRegion_0__8->SetLineColor(ci);
   boosted_data_control_region_ControlRegion_0__8->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   boosted_data_control_region_ControlRegion_0__8->SetMarkerColor(ci);
   boosted_data_control_region_ControlRegion_0__8->SetMarkerStyle(20);
   boosted_data_control_region_ControlRegion_0__8->GetXaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__8->GetXaxis()->SetLabelSize(0.12);
   boosted_data_control_region_ControlRegion_0__8->GetXaxis()->SetTitleSize(0.085);
   boosted_data_control_region_ControlRegion_0__8->GetXaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__8->GetYaxis()->SetTitle("Data/Expected");
   boosted_data_control_region_ControlRegion_0__8->GetYaxis()->SetNdivisions(5);
   boosted_data_control_region_ControlRegion_0__8->GetYaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__8->GetYaxis()->SetLabelSize(0.1);
   boosted_data_control_region_ControlRegion_0__8->GetYaxis()->SetTitleSize(0.12);
   boosted_data_control_region_ControlRegion_0__8->GetYaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__8->GetYaxis()->SetTitleOffset(0.25);
   boosted_data_control_region_ControlRegion_0__8->GetZaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__8->GetZaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_0__8->GetZaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_0__8->GetZaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__8->Draw("");
   Double_t xAxis9[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *OneWithError_boosted_data_control_region_ControlRegion_0__9 = new TH1F("OneWithError_boosted_data_control_region_ControlRegion_0__9","",6, xAxis9);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetBinContent(1,1);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetBinContent(2,1);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetBinContent(3,1);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetBinContent(4,1);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetBinContent(5,1);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetBinContent(6,1);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetBinError(1,0.0206586);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetBinError(2,0.03229028);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetBinError(3,0.05025668);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetBinError(4,0.06922042);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetBinError(5,0.1037742);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetBinError(6,0.1040146);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetMinimum(0.21);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetMaximum(1.79);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetEntries(1237.079);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetDirectory(0);

   ci = TColor::GetColor("#ccccff");
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetFillColor(ci);

   ci = TColor::GetColor("#ccccff");
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetLineColor(ci);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetMarkerColor(ci);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetMarkerStyle(20);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->SetMarkerSize(0);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->GetXaxis()->SetLabelFont(42);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->GetXaxis()->SetLabelSize(0.12);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->GetXaxis()->SetTitleSize(0.085);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->GetXaxis()->SetTitleFont(42);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->GetYaxis()->SetTitle("Data/Bkg");
   OneWithError_boosted_data_control_region_ControlRegion_0__9->GetYaxis()->SetNdivisions(5);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->GetYaxis()->SetLabelFont(42);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->GetYaxis()->SetLabelSize(0.1);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->GetYaxis()->SetTitleSize(0.12);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->GetYaxis()->SetTitleFont(42);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->GetZaxis()->SetLabelFont(42);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->GetZaxis()->SetLabelSize(0.035);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->GetZaxis()->SetTitleSize(0.035);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->GetZaxis()->SetTitleFont(42);
   OneWithError_boosted_data_control_region_ControlRegion_0__9->Draw("sameE2");
   TLine *line = new TLine(250,1,1000,1);
   line->SetLineStyle(2);
   line->SetLineWidth(2);
   line->Draw();
   Double_t xAxis10[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_data_control_region_ControlRegion_0__10 = new TH1F("boosted_data_control_region_ControlRegion_0__10","",6, xAxis10);
   boosted_data_control_region_ControlRegion_0__10->SetBinContent(1,1.005281);
   boosted_data_control_region_ControlRegion_0__10->SetBinContent(2,1.009377);
   boosted_data_control_region_ControlRegion_0__10->SetBinContent(3,0.9861652);
   boosted_data_control_region_ControlRegion_0__10->SetBinContent(4,0.9889661);
   boosted_data_control_region_ControlRegion_0__10->SetBinContent(5,0.978512);
   boosted_data_control_region_ControlRegion_0__10->SetBinContent(6,0.9897881);
   boosted_data_control_region_ControlRegion_0__10->SetBinError(1,0.02096155);
   boosted_data_control_region_ControlRegion_0__10->SetBinError(2,0.03286983);
   boosted_data_control_region_ControlRegion_0__10->SetBinError(3,0.04912439);
   boosted_data_control_region_ControlRegion_0__10->SetBinError(4,0.07475881);
   boosted_data_control_region_ControlRegion_0__10->SetBinError(5,0.1020169);
   boosted_data_control_region_ControlRegion_0__10->SetBinError(6,0.0943726);
   boosted_data_control_region_ControlRegion_0__10->SetMinimum(0.21);
   boosted_data_control_region_ControlRegion_0__10->SetMaximum(1.79);
   boosted_data_control_region_ControlRegion_0__10->SetEntries(1231.079);
   boosted_data_control_region_ControlRegion_0__10->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   boosted_data_control_region_ControlRegion_0__10->SetLineColor(ci);
   boosted_data_control_region_ControlRegion_0__10->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   boosted_data_control_region_ControlRegion_0__10->SetMarkerColor(ci);
   boosted_data_control_region_ControlRegion_0__10->SetMarkerStyle(20);
   boosted_data_control_region_ControlRegion_0__10->GetXaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__10->GetXaxis()->SetLabelSize(0.12);
   boosted_data_control_region_ControlRegion_0__10->GetXaxis()->SetTitleSize(0.085);
   boosted_data_control_region_ControlRegion_0__10->GetXaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__10->GetYaxis()->SetTitle("Data/Bkg");
   boosted_data_control_region_ControlRegion_0__10->GetYaxis()->SetNdivisions(5);
   boosted_data_control_region_ControlRegion_0__10->GetYaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__10->GetYaxis()->SetLabelSize(0.1);
   boosted_data_control_region_ControlRegion_0__10->GetYaxis()->SetTitleSize(0.12);
   boosted_data_control_region_ControlRegion_0__10->GetYaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__10->GetZaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__10->GetZaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_0__10->GetZaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_0__10->GetZaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__10->Draw("same");
   Double_t xAxis11[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_data_control_region_ControlRegion_0__11 = new TH1F("boosted_data_control_region_ControlRegion_0__11","",6, xAxis11);
   boosted_data_control_region_ControlRegion_0__11->SetBinContent(1,1.159618);
   boosted_data_control_region_ControlRegion_0__11->SetBinContent(2,1.059605);
   boosted_data_control_region_ControlRegion_0__11->SetBinContent(3,0.953604);
   boosted_data_control_region_ControlRegion_0__11->SetBinContent(4,0.841091);
   boosted_data_control_region_ControlRegion_0__11->SetBinContent(5,0.8662208);
   boosted_data_control_region_ControlRegion_0__11->SetBinContent(6,1.176001);
   boosted_data_control_region_ControlRegion_0__11->SetBinError(1,0.02417971);
   boosted_data_control_region_ControlRegion_0__11->SetBinError(2,0.03450549);
   boosted_data_control_region_ControlRegion_0__11->SetBinError(3,0.04750239);
   boosted_data_control_region_ControlRegion_0__11->SetBinError(4,0.0635805);
   boosted_data_control_region_ControlRegion_0__11->SetBinError(5,0.09030976);
   boosted_data_control_region_ControlRegion_0__11->SetBinError(6,0.1121273);
   boosted_data_control_region_ControlRegion_0__11->SetEntries(1273.385);
   boosted_data_control_region_ControlRegion_0__11->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   boosted_data_control_region_ControlRegion_0__11->SetLineColor(ci);
   boosted_data_control_region_ControlRegion_0__11->SetLineWidth(2);

   ci = TColor::GetColor("#ff0000");
   boosted_data_control_region_ControlRegion_0__11->SetMarkerColor(ci);
   boosted_data_control_region_ControlRegion_0__11->SetMarkerStyle(20);
   boosted_data_control_region_ControlRegion_0__11->GetXaxis()->SetTitle("fake MET (GeV)");
   boosted_data_control_region_ControlRegion_0__11->GetXaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__11->GetXaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_0__11->GetXaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_0__11->GetXaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__11->GetYaxis()->SetTitle("Events/GeV");
   boosted_data_control_region_ControlRegion_0__11->GetYaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__11->GetYaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_0__11->GetYaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_0__11->GetYaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__11->GetZaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__11->GetZaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_0__11->GetZaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_0__11->GetZaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__11->Draw("pelsame");
   Double_t xAxis12[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_data_control_region_ControlRegion_0__12 = new TH1F("boosted_data_control_region_ControlRegion_0__12","",6, xAxis12);
   boosted_data_control_region_ControlRegion_0__12->SetBinContent(1,1.005281);
   boosted_data_control_region_ControlRegion_0__12->SetBinContent(2,1.009377);
   boosted_data_control_region_ControlRegion_0__12->SetBinContent(3,0.9861652);
   boosted_data_control_region_ControlRegion_0__12->SetBinContent(4,0.9889661);
   boosted_data_control_region_ControlRegion_0__12->SetBinContent(5,0.978512);
   boosted_data_control_region_ControlRegion_0__12->SetBinContent(6,0.9897881);
   boosted_data_control_region_ControlRegion_0__12->SetBinError(1,0.02096155);
   boosted_data_control_region_ControlRegion_0__12->SetBinError(2,0.03286983);
   boosted_data_control_region_ControlRegion_0__12->SetBinError(3,0.04912439);
   boosted_data_control_region_ControlRegion_0__12->SetBinError(4,0.07475881);
   boosted_data_control_region_ControlRegion_0__12->SetBinError(5,0.1020169);
   boosted_data_control_region_ControlRegion_0__12->SetBinError(6,0.0943726);
   boosted_data_control_region_ControlRegion_0__12->SetMinimum(0.21);
   boosted_data_control_region_ControlRegion_0__12->SetMaximum(1.79);
   boosted_data_control_region_ControlRegion_0__12->SetEntries(1231.079);
   boosted_data_control_region_ControlRegion_0__12->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   boosted_data_control_region_ControlRegion_0__12->SetLineColor(ci);
   boosted_data_control_region_ControlRegion_0__12->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   boosted_data_control_region_ControlRegion_0__12->SetMarkerColor(ci);
   boosted_data_control_region_ControlRegion_0__12->SetMarkerStyle(20);
   boosted_data_control_region_ControlRegion_0__12->GetXaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__12->GetXaxis()->SetLabelSize(0.12);
   boosted_data_control_region_ControlRegion_0__12->GetXaxis()->SetTitleSize(0.085);
   boosted_data_control_region_ControlRegion_0__12->GetXaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__12->GetYaxis()->SetTitle("Data/Bkg");
   boosted_data_control_region_ControlRegion_0__12->GetYaxis()->SetNdivisions(5);
   boosted_data_control_region_ControlRegion_0__12->GetYaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__12->GetYaxis()->SetLabelSize(0.1);
   boosted_data_control_region_ControlRegion_0__12->GetYaxis()->SetTitleSize(0.12);
   boosted_data_control_region_ControlRegion_0__12->GetYaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__12->GetZaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__12->GetZaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_0__12->GetZaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_0__12->GetZaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__12->Draw("samepel");
   Double_t xAxis13[7] = {250, 300, 350, 400, 450, 500, 1000}; 
   
   TH1F *boosted_data_control_region_ControlRegion_0__13 = new TH1F("boosted_data_control_region_ControlRegion_0__13","",6, xAxis13);
   boosted_data_control_region_ControlRegion_0__13->SetBinContent(1,1.005281);
   boosted_data_control_region_ControlRegion_0__13->SetBinContent(2,1.009377);
   boosted_data_control_region_ControlRegion_0__13->SetBinContent(3,0.9861652);
   boosted_data_control_region_ControlRegion_0__13->SetBinContent(4,0.9889661);
   boosted_data_control_region_ControlRegion_0__13->SetBinContent(5,0.978512);
   boosted_data_control_region_ControlRegion_0__13->SetBinContent(6,0.9897881);
   boosted_data_control_region_ControlRegion_0__13->SetBinError(1,0.02096155);
   boosted_data_control_region_ControlRegion_0__13->SetBinError(2,0.03286983);
   boosted_data_control_region_ControlRegion_0__13->SetBinError(3,0.04912439);
   boosted_data_control_region_ControlRegion_0__13->SetBinError(4,0.07475881);
   boosted_data_control_region_ControlRegion_0__13->SetBinError(5,0.1020169);
   boosted_data_control_region_ControlRegion_0__13->SetBinError(6,0.0943726);
   boosted_data_control_region_ControlRegion_0__13->SetMinimum(0.21);
   boosted_data_control_region_ControlRegion_0__13->SetMaximum(1.79);
   boosted_data_control_region_ControlRegion_0__13->SetEntries(1231.079);
   boosted_data_control_region_ControlRegion_0__13->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   boosted_data_control_region_ControlRegion_0__13->SetLineColor(ci);
   boosted_data_control_region_ControlRegion_0__13->SetLineWidth(2);

   ci = TColor::GetColor("#0000ff");
   boosted_data_control_region_ControlRegion_0__13->SetMarkerColor(ci);
   boosted_data_control_region_ControlRegion_0__13->SetMarkerStyle(20);
   boosted_data_control_region_ControlRegion_0__13->GetXaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__13->GetXaxis()->SetLabelSize(0.12);
   boosted_data_control_region_ControlRegion_0__13->GetXaxis()->SetTitleSize(0.085);
   boosted_data_control_region_ControlRegion_0__13->GetXaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__13->GetYaxis()->SetTitle("Data/Bkg");
   boosted_data_control_region_ControlRegion_0__13->GetYaxis()->SetNdivisions(5);
   boosted_data_control_region_ControlRegion_0__13->GetYaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__13->GetYaxis()->SetLabelSize(0.1);
   boosted_data_control_region_ControlRegion_0__13->GetYaxis()->SetTitleSize(0.12);
   boosted_data_control_region_ControlRegion_0__13->GetYaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__13->GetZaxis()->SetLabelFont(42);
   boosted_data_control_region_ControlRegion_0__13->GetZaxis()->SetLabelSize(0.035);
   boosted_data_control_region_ControlRegion_0__13->GetZaxis()->SetTitleSize(0.035);
   boosted_data_control_region_ControlRegion_0__13->GetZaxis()->SetTitleFont(42);
   boosted_data_control_region_ControlRegion_0__13->Draw("sameaxis");
   p2->Modified();
   c_ControlRegion_0->cd();
   tex = new TLatex(0.7,0.03,"fake MET (GeV)");
   tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
//   tex = new TLatex(0.1,0.1,"Data/Expected");
//   tex->SetNDC();
//   tex->SetTextAngle(90);
//   tex->SetTextFont(42);
//   tex->SetTextSize(0.03);
//   tex->SetLineWidth(2);
//   tex->Draw();
   c_ControlRegion_0->Modified();
   c_ControlRegion_0->cd();
   c_ControlRegion_0->SetSelected(c_ControlRegion_0);
   c_ControlRegion_0->SaveAs("post_fit_photon_boosted.pdf");
}
